### ISSUE TITLE
Auto scrolling causes crash when placing parts on bounds

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1016]
_From [osborn.s...@gmail.com](https://code.google.com/u/104140948946445145303/) on March 06, 2010 23:22:02_

Same issue mentioned in the forums: http://fritzing.org/forum/thread/208/ Video: http://blip.tv/file/3299609 The previous changeset seems to make things somewhat better for the right
most bounds, but this bug is still easy to reproduce.

Previous changeset: https://code.google.com/p/fritzing/source/detail?r=4027

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1016_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
