### ISSUE TITLE
export to cnc (and other formats)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1033]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 31, 2010 07:42:55_

is this basically a gerber format and if so, how does it differ from the 
current gerber export

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1033_

**Comment by failiz** [comment]
I do not think that this is a good idea. There are several programs to do that. It would be a lot of work for a narrow case (the fabrication prices have dropped a lot). I would prefer that we keep with a small and easy to use program that is really good, instead of a big program with several issues/bugs.
