### ISSUE TITLE
Advanced post-it notes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1041]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 06, 2010 12:47:53_

Just re-discovered Dirk's original design specs for notes on the server. 
Putting this reminder here to look at them once we have time for this 
feature.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1041_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.

It would be helpful if the issue contained the spec or a link.


  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
