### ISSUE TITLE
export to svg: copper and silkscreen colors aren't being modified when part svg files are loaded

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1050]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 13, 2010 04:22:53_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1050_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
