### ISSUE TITLE
translate problem with importing the attached smd file

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1274]
_From [daniel.t...@ixds.de](https://code.google.com/u/109739317909807101336/) on October 20, 2010 12:54:20_

a

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1274_

**Comment by failiz** [comment]
This may still be relevant and probably not addressed yet. "The second deeper problem may be a bug in Qt. The way you apply a transform (like a flip) to an object is you apply the transform to the center of the object. We find the center of the object by using QSvgRenderer::boundsOnElement. In those same two files, an internal transform had moved the bounds to a negative offset, but boundsOnElement returned an offset of zero (ish). By contrast, a positive internal transform seems to result in the bounds starting with a positive offset. Further investigation is needed to determine whether this is indeed a bug or not."
Change the title of the issue?

**Comment by KjellMorgenstern** [comment]
We have perpared several improvements for the svg handling, one that collects transforms along the tree, and one which correctly calculates matrix transforms for combinations of translate, rotate, scale and mirror.
Since this issue does not provide means to confirm or falsify, I just assume that those improvements will also cover this issue.
