### ISSUE TITLE
check disconnect/reconnect behavior when changing voltage on a power symbol

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1326]
_From [tjtomk...@gmail.com](https://code.google.com/u/115783105138156191836/) on January 22, 2011 05:01:12_

What steps will reproduce the problem? 1. Create a small circuit using power.fpz
2. Modify power value to 3.3 or 12 volts
3. Try to save circuit

What is the expected output? 
Expected outcome is a saved circuit.

What do you see instead?
The application crashes.

What version of the product are you using?
Fritzing 0.4.4 (b4641)

On what operating system?
OSX 10.6.6 Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1326_

**Comment by failiz** [comment]
When changing the voltage in a power symbol, the wires which were connected to it are deleted. This still happens in 0.9.4. However, I think this is not the right behaviour. Users should known what they are doing and if you put the power pin, wire it and then change the voltage you have to wire it again.
The previous argument ("Because it could lead to a situation where some parts are connected to two voltages") does not seem coherent when you can connect two power symbols with different voltage to the same net and Fritzing does not complain at all.

**Comment by failiz** [comment]
Remove imported label and add schematic view

**Comment by failiz** [comment]
This is caused by function SchematicSketchWidget::setVoltage(double v, bool doEmit)
This is the code:
```

	QUndoCommand * parentCommand =  new QUndoCommand();
	parentCommand->setText(tr("Change voltage from %1 to %2").arg(sitem->voltage()).arg(v));

	new CleanUpWiresCommand(this, CleanUpWiresCommand::UndoOnly, parentCommand);
	new CleanUpRatsnestsCommand(this, CleanUpWiresCommand::UndoOnly, parentCommand);

	QList<Wire *> done;
	foreach (ConnectorItem * toConnectorItem, sitem->connector0()->connectedToItems()) {
		Wire * w = qobject_cast<Wire *>(toConnectorItem->attachedTo());
		if (w == NULL) continue;
		if (done.contains(w)) continue;

		QList<ConnectorItem *> ends;
		removeWire(w, ends, done, parentCommand);
	}

	new SetPropCommand(this, item->id(), "voltage", QString::number(sitem->voltage()), QString::number(v), true, parentCommand);

	new CleanUpRatsnestsCommand(this, CleanUpWiresCommand::RedoOnly, parentCommand);
	new CleanUpWiresCommand(this, CleanUpWiresCommand::RedoOnly, parentCommand);

	m_undoStack->waitPush(parentCommand, PropChangeDelay);
```
The if we remove the loop that removes the wires, the issue is that the ratsnets are not updated when you change to BB or PCB view. @KjellMorgenstern , any ideas about how to fix this? There are CleanUpRatsnestsCommand and CleanUpWiresCommand before and after the setPropCommand, but they do not have any effect.

The issue is the same in #2669, but in the SchematicSketchWidget::setProp(ItemBase * itemBase, const QString & prop, const QString & trProp, const QString & oldValue, const QString & newValue, bool redraw) function.
