### ISSUE TITLE
Changing a part's properties very fast causes copies of the part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1431]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 21, 2011 06:18:59_

What steps will reproduce the problem? 1. Place a part (e.g., a transistor)
2. Move your mouse cursor over a property that uses the swap mechanism (e.g. 'package').
3. Use the mousewheel, scrolling up and down fast. What is the expected output? What do you see instead? The part gets copied multiple times (on top of one another). It seems like the swapping mechanism isn't catching up.

This is nasty if you're doing that in a breadboard and not noticing the copy. It will be quite confusing.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1431_

**Comment by failiz** [comment]
This is still an issue. I can observe this behaviour with transistors and potentiometers. 
I would disable the wheel. It does not take to much time to select from a combo box and this behaviour is quite prone to errors. The wheel scrolling moves the view of the inspector up and down. And if the mouse is suddenly over a combo box, the next scroll changes its value.  And this can happen without the user noticing it.

**Comment by failiz** [comment]
@KjellMorgenstern , should we disable wheel events to change properties in the comboboxes?

This issue looks that can be fixed by increasing the timer from 30 to 200 (with 100ms I was still getting duplicated parts). However, I think that updating properties unintentionally can happen when scrolling through the inspector pane. Thus, I am more inclined towards deactivating the wheel scrolling to change properties. 

Another solution would be to change the focus policy. So a combobox needs to be pressed in order to scroll with the wheel of the mouse. However, I tried that and it does not work (without adding other code) as when the property changes with the first wheel movement, the combobox looses focus again.

**Comment by failiz** [comment]
I think this has been fixed in 1.0.0

**Comment by KjellMorgenstern** [comment]
We disabled the wheel input on comboboxes in the inspector to avoid accidental changes.
Plus, we fixed the combination of timers that was used to trigger the part change. 

It was reliably reproducible when switching (by pressing a key or a mousewheel) parts slower than 30ms, but faster than 130ms. User would not often do this, but certainly this happened.

So even if you trigger switching parts by other means, the switch will now happen more instant, and will not "forget" to delete the previous part.
