### ISSUE TITLE
request to "fab/launched" now contains params which it would be nice to record in a database

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1615]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 07, 2011 15:06:59_

When Fritzing launches, it sends a request to fab.fritzing.org/launched.  Originally this was to determine whether it was ok to display the fab ordering button.  Now Fritzing doesn't need to check, but we would repurpose the request to collect some data. Pid is unique per machine, version is the Fritzing version.

?pid=86261f422b019292ca56b776e3ea7e06&version=0.6.3b.08.05.5346&sysname=Windows&kernname=NT&kernversion=6.1arch=i386&sysversion=7&#37;20&#37;2F&#37;20Server&#37;202008&#37;20R2

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1615_

**Comment by failiz** [comment]
The code is still there. I would prefer to remove it. If we keep it, we should inform the users and specify what kind of information we are sending. And we should check that this complies with the GDPR.

**Comment by KjellMorgenstern** [comment]
This issue is outdated in multiple ways. For GDPR compliance, we should of course not store IP addresses and not generated IDs. We don't  generate/record those, except if we detect spam/scams/attacks. I disabled the google analytics, and the new website works without google ads thanks to the paywall.  The endpoint for this particular call is currently not in use (404). Closing this issue. Work on the Fab API should be done with great care, as we can't fix it once a release it out.
