### ISSUE TITLE
provide a link from each core part to a shop where the user can buy it

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1844]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 09, 2012 05:01:13_

http://fritzing.org/forum/thread/770 This is related to issue 1283 , but with a different emphasis. Recommending a shop would make the overall process easier so it's in line with the general goals of Fritzing. But it is also potentially stamping the shop with a Fritzing seal of approval (unless we carefully make clear that buyers are at their own risk).

However, it is also a powerful opportunity to monetize such a link. Akin to targeted advertising in Google, but with a very high relevance ranking.  I am not sure how I feel about this idea though.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1844_

**Comment by failiz** [comment]
I think that it would be a nice feature. Instead of a link for each part, I would have a button in the program (next no manufacture) called buy parts for the PCB. After clicking in the button, you can see different shops, the parts they have available and the price. And of course, you could place the order. The shops will check that their parts match the footprints. And it would be a nice way to generate some cash to help the project (percentage of the sells or shops pay a fix amount every year to appear in the list).

**Comment by failiz** [comment]
ping

**Comment by KjellMorgenstern** [comment]
This requires a shop to partner with, at least something like amazon affiliates, or a store specialized on electronics. There is also a regional dependency, stores work different across the globe. How that would look on the Fritzing application might be very different depending on the solution and partners found. Therefore, closing this for now, it's an interesting concept, but first needs planning before there is anything we can put in code.
