### ISSUE TITLE
possible platform dependent bug in gerber export?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2025]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 11, 2012 02:43:20_

see http://fritzing.org/forum/thread/955

**Attachment:** [example-circuit.fzz example-circuit.zip](http://code.google.com/p/fritzing/issues/detail?id=2025)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2025_

**Comment by failiz** [comment]
Not file available, not enough info and no replicable in 2014.

From the forum:
"I didn't see this issue mentioned in your Google Code tracker, but didn't add it there since I don't have (nor want) a Google Account[TM]. Running 0.74b4.10 on Linux (32-bit Intel), if I export to Gerber and open with gerbv 2.6.0 (Debian) or gerber-viewer.com (linked from your FAQ) the lead placement for pin #2 of every through-hole resistor and ceramic capacitor is misplaced on all layers, though other components appear to be unaffected. Will this adversely affect any fabrication orders I attempt to place through Fritzing Fab? Fritzing itself displays the PCB view correctly, as does an etchable PDF export. I'm linking screen captures of a simple PCB from Fritzing and gerbv to demonstrate.

Fritzing PCB looks fineGerber export does not

Thanks for a great application and service!"
