### ISSUE TITLE
double-row tht pinheaders: male, female, female rounded

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2043]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 18, 2012 06:58:14_

pcb and breadboard view just double; schematic just gets longer

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2043_

**Comment by osamuaoki** [comment]
This is important to get it right for BREADBOARD since these are basic parts.

With 0.9.0b and 0.9.2b (as packaged by Debian, in 2014-2015 time), I still see issues to make double raw male and female connectors.

* Breadboard: BAD: 
 * female: single raw, pin spacing never changes
 * male: double raw but pin spacing is constant
* Schematics: No-so-nice
 * female and male: single raw (I think it should be double raw or selectable.)
* Breadboard: Nice
 * female and male: double raw with proper pin spacing of pins

This pin spacing issue with BREADBOARD view is with other connector components such as screw terminal.  I expected double pitch pins should appear 0.2 inch spacing.

Another pin spacing issue with BREADBOARD view is with register.  Chose 100mil stand up or 800mil, it does not get reflected .  Of course legs for register can be stretched and bent manually.  But  that does not excuse us to provide the same register shape for BREADBOARD. 

These needs good attention :-)

**Comment by osamuaoki** [comment]
Hi,

I at least found fix for most annoying part of the issues.  The BREADBOARD issue with female double raw connector can be fixed by reactivating commented out code.  Good enough for me but why this is disabled )or intentionally broken) is misery.

```
--- fritzing-0.9.2b+dfsg.orig/src/items/pinheader.cpp
+++ fritzing-0.9.2b+dfsg/src/items/pinheader.cpp
@@ -686,7 +686,7 @@ QString PinHeader::makeBreadboardSvg(con
                return makeBreadboardShroudedSvg(pins);
        }
     if (expectedFileName.contains("double") && !expectedFileName.contains("smd"
, Qt::CaseInsensitive)) {
-        //return makeBreadboardDoubleSvg(expectedFileName, pins);
+        return makeBreadboardDoubleSvg(expectedFileName, pins);
     }
     
        double unitHeight = 0.1;  // inches
```

**Comment by aknoerig** [comment]
Thanks, can you make a pull request for this? 
There probably was a reason to comment out this part, so it would be great if you could test all cases in all views.
When the pin spacing is changed, we sometimes do not change the image for breadboard view because it wouldn't fit. For example when you set the screw terminal to 3.5mm spacing, it wouldn't fit into the breadboard anymore. So we keep it at 0.1" in breadboard view, and only change PCB view. 
This might be confusing, but is practical.

**Comment by osamuaoki** [comment]
Hi,

On Mon, Aug 10, 2015 at 01:22:00AM -0700, Andr� Kn�rig wrote:
> Thanks, can you make a pull request for this?

I will ...

> There probably was a reason to comment out this part, so it would be
> great if you could test all cases in all views.

I thought about this too ... I need some time though

> When the pin spacing is changed, we sometimes do not change the image
> for breadboard view because it wouldn't fit. For example when you set
> the screw terminal to 3.5mm spacing, it wouldn't fit into the
> breadboard anymore. So we keep it at 0.1" in breadboard view, and only
> change PCB view.  This might be confusing, but is practical.

This is very confusing too.

3.5 mm pitch can fit roughly into BB if tilted to 45 degree :-)

0.1" = 2.54mm BB pitch -> 3.59 mm pitch at 45 degree

BB view is basically top view.  It is also useful for the perfboard.  In
such case, we can drill extra hole too.

Osamu
