### ISSUE TITLE
HELLO.FZZ opens Untitled Sketch.fzz

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2141]
_From [jrobin...@kitchenpages.com](https://code.google.com/u/115804952137586310927/) on July 27, 2012 15:06:50_

Steps will reproduce the problem are:
1. Open fritzing, create a PCB design/or load one, save file as xyz.fzz to the desktop, etc. Close.
2. Rename the xyz.fzz file to HELLO.FZZ
3. Open HELLO.FZZ with fritzing

The expected result was to see the PCB. 
Instead fritzing shows a empty, blank PCB design, and title bar showing the file name of - Untitled Sketch.fzz

Work-around: Rename/Save with the file extension of .fzz

Version: Fritzing 0.7.5
Operating System: Windows Xp sp2

Seems to only be a issue if the filename extension is uppercase.

When saving as a .FZZ from the fritzing interface - the final file name will be appended with a lowercase .fzz extension to result in a file of HELLO.FZZ.fzz to archive HELLO.FZZ.fz

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2141_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
