### ISSUE TITLE
collectLeaves will miss text elements

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2231]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 01, 2012 08:19:30_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2231_

**Comment by KjellMorgenstern** [comment]
While this is true (collectLeaves is a method of TextUtils), it is not clear if this causes any issues.
The outline method for the gerber generator alread implements a workaround:
```
	TextUtils::collectLeaves(root, leaves);
	QDomNodeList textNodes = root.elementsByTagName("text");
	for (int t = 0; t < textNodes.count(); t++) {
		leaves << textNodes.at(t).toElement();
	}

```

**Comment by failiz** [comment]
Did you document this in the code? 
I would refactor the code to have a collectLeavesExceptTextElements (the current collectLeaves function) and a collectAllLeavesElements (the current workaround). So, it is clear what each function does.

**Comment by KjellMorgenstern** [comment]
I think the problem is the distinction between QDomNode and QDomElements (and further QDomText ).
The method checks for hasChildNodes(), but then recourses depth first into childElements (not nodes!)

There are no "text elements" in QDomDocument, it is either QDomElement or QDomText.  SVG however has QDomElements that are named "text". Those then can have QChildNodes which are QDomText.
I think something like this

`<text> Hello World </text>`

QDomElement: text
QDomText: Hello World

And there could be multiple QDomText child nodes, maybe if the text contains a newline, but the existence of the normalize() method is a hint that this is arbitrary. Edit: A text interrupted with a comment blocks would be a better explanation for multiple QDomText node childs.

I'd rather not modify anything without use cases and examples for the uses of collectLeaves.
