### ISSUE TITLE
via to bendpoint glitches

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2261]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 14, 2012 05:06:40_

http://fritzing.org/forum/thread/1180

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2261_

**Comment by failiz** [comment]
From the forum: "Just reporting what I think is a rather (low-priority) bug:

When converting a 90 degree bendpoint _|, if you zoom in as you do it, you'll notice that it'll shift a bit down and to the right. Thankfully, converting a via back to a bend point doesn't exhibit this shifting bug.

(It's especially annoying for perfectionists when manually routing traces, since there doesn't appear to be a way to re-snap the via to a perfect 22.5/45/90 degree increment when holding shift while dragging it)

However, when changing it back to a bendpoint, it has a display glitch that doesn't go away unless you move the bendpoint wires or re-open the fritzing sketch."

I could not replicate this in 0.9.6.
