### ISSUE TITLE
Spurious object in Gerber top copper

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2269]
_From [boo...@nc.rr.com](https://code.google.com/u/108888894911553875363/) on October 18, 2012 15:15:49_

What steps will reproduce the problem? 1. Open the attached .fzz
2. Export for Production>Gerber Extended
3. Use a Gerber viewer (I used GerbV) to view the top copper. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? See a spurious rectangle, circled in the attached screenshot. What version of Fritzing are you using? On what operating system? 7.10b on Ubuntu 12.04 Please provide any additional information below. The spurious object is NOT in PDF from "Export for PCB."  So I suppose this is not a critical issue as long as the Fritzing fab is not using the Gerber.

GerbV will identify the spurious object but the information it gives (something about unidentified net?) doesn't help figure out where the object derives.

Note there are three custom parts, and they are also an issue: opening the sketch gives "Can't find the following ... parts" for some of the parts.  As discussed in the forums under "Resolving discepancies.." where I first reported this issue.

**Attachment:** [Screenshot from 2012-10-18 15:02:42.png MyBQv6.fzz](http://code.google.com/p/fritzing/issues/detail?id=2269)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2269_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
You can help progress the issue by providing additional information:
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
