### ISSUE TITLE
warn users about coreldraw images not saved in presentation mode

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2321]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 29, 2012 05:44:56_

use wording from http://fritzing.org/forum/thread/561/?page=all

**Attachment:** [svg.pcb.1.5___11W_Resistor__ed7b3241c488a48a9f28__pcb__fd34f8a397a8fa7450748c9c04ae339e.svg](http://code.google.com/p/fritzing/issues/detail?id=2322)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2322_

**Comment by failiz** [comment]
From the old forum:
Views: 2991

Latest post time: 2012-11-25 09:14:40 UTC

Author: 2526

Body:

Hello!

I am trying to create a device using Sparkfun's 2x2 button pad and breakout PCB.

I imported the Eagle schematics for the PCB into Corel Draw, so I could create an accurate SVG file for use in Fritzing. My ultimate aim is to incorporate the breakout PCB into once created via Frizing.

Unfortunately, even though I follow th etemplate, and my graphic seems to import correctly, the copper traces comes out all black on the PCD view. In the image bleow, you can see the part view on the left and the actual PCB view on the right...



 

I can't work out what I'm doing wrong. All the connectors work, but the copper is filled in all black.

I also need to incorporate holes and traces (on both sides) into the PCB part, so that it matches the schematic from Sparkfun.

Any tips would be most welcome.

I hope to create a few cool parts and share them with the community. I've already had some success creating softpots...



Thanks in advance for your help!

:)

Dan

Time: 2011-07-28 07:44:03 UTC

Edited at:

Author: 8

Body:

Hi Dan,

It's hard to tell--could well be a bug in the parts editor.  Could you either export the part (i.e. select the part, and choose "Export" from the Part menu), or drop the part into a sketch and save the sketch as shareable (under the File menu), and then email the resulting file to info .at. fritzing .dot. org?  We'll take a look and see if we can figure out the problem.

Cheers,

- j

 

Time: 2011-07-28 08:51:38 UTC

Edited at:

Author: 2526

Body:

Thanks, Jon - I've e-mailed the sketch over to you.

:)

Dan

Time: 2011-07-28 16:52:14 UTC

Edited at:

Author: 8

Body:

Just to close the loop here, the PCB SVG image was produced with Corel Draw, and the SVG style is very different from Inkscape or Illustrator.  So the usual internal image manipulations that Fritzing performs failed.

I don't know whether it's possible to set SVG image type when exporting from Corel (for example whether you are able to request "SVG 1.2 Tiny"), and even if so, whether those images are more in a style that Fritzing is used to.

Cheers,

 

- j

Time: 2011-07-29 13:19:26 UTC

Edited at:

Author: 2526

Body:

Thanks, Jon.

It seems that, when exporting from Corel Draw, the trick is to select Presentation Attributes in the Styling Options drop-down.



Corel needs this attribute set correctly to export Fritzing-freindly SVG files.

:)

**Comment by failiz** [comment]
Is this still relevant? It seems that the warning is now in parts editor and logoitem. In any case, it's not a fritzing bug and coral draw is not very popular at the moment (i think)

**Comment by KjellMorgenstern** [comment]
In general, we need more SVG sanity checks (e.g. warn about certain SVG 2.0 features). But for CorelDraw in combination with the current parts editor in Fritzing, I think we can close this.
