### ISSUE TITLE
change weight of ratsnest display

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2327]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 04, 2012 05:03:35_

http://fritzing.org/forum/thread/126

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2328_

**Comment by KjellMorgenstern** [comment]
The linked thread is no longer available.

This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
