### ISSUE TITLE
drc missing holes in some circumstances

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2338]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 14, 2012 07:24:32_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

**Attachment:** [drc missing holes.fzz](http://code.google.com/p/fritzing/issues/detail?id=2339)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2339_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
