### ISSUE TITLE
ratsnest is not shown for smd part placed on bottom layer

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2349]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 30, 2012 02:43:04_

http://fritzing.org/forum/thread/1285/

**Attachment:** [16x Modulierte from the scratch with rats net shown on Copper1.fzz 16x Modulierte from the scratch without rats net shown on Copper0.fzz ratsnest.png](http://code.google.com/p/fritzing/issues/detail?id=2350)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2350_

**Comment by failiz** [comment]
From the developer in th eold forum: " I open the "no rats" file, reposition the SOT-23 once (so the rats are visible) and save, then the ratsnests are visible in all subsequent saves and reloads of the file no matter how many times I change between copper1 and copper0"
So, no file to debug (which contained a custom part) and the issue was not reproducible. Close
