### ISSUE TITLE
Fritzing crashes saving modified parts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2368]
_From [golczew...@gmail.com](https://code.google.com/u/116618479639276889546/) on January 09, 2013 20:21:46_

What steps will reproduce the problem? 1. Drag a female header part, and change it to 5 pins
2. Modify metadata to change title and description.
3. Modify each pin description (eg. pin1 -> 5v, pin2 -> GND, pin 3 -> Rx, pin 4 -> Tx, pin 5 -> 1PPS)
4. Save as new part

Fritzing crashes.

Running on OS X Lion 10.7.5, 16GB of memory, 2011 MacBook Pro.

Sketch has Seeedstudio Arduino Mega, short breadboard, XBee module and some wires hooking up the data.  See attached sketch file.

Also see crash dump text file before reporting to Apple.

Using latest version of Fritzing (7.11b).

**Attachment:** [ExampleSketch.fzz CrashDump-Fritzing-7.11b.txt](http://code.google.com/p/fritzing/issues/detail?id=2369)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2369_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
You can help progress the issue by providing additional information:
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
