### ISSUE TITLE
language breaks DRC under linux

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2385]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 16, 2013 23:57:31_

"I'm using en_DK.ISO-8859-15 as the default. However, I tried running
Fritzing with LANG=C and the DRC issue disappeared right away."

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2386_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
You can help progress the issue by providing additional information:
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
