### ISSUE TITLE
unable to easily remove terminal points in parts editor

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2399]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 25, 2013 01:55:03_

try clicking on "center" and doing "save as new part" but terminal point does not disappear

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2400_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
You can help progress the issue by providing additional information:
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
