### ISSUE TITLE
custom part appears in both Mine and temp bins

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2437]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 27, 2013 04:51:30_

http://fritzing.org/forum/thread/1405

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2439_

**Comment by failiz** [comment]
From the old forum:
"I'm not sure if it's really a bug or a feature...

What I've experienced is that, after adding a custom part (from Mine bin) in a new project, it will be replicated in the Temp bin.

How to reproduce:

- edit a Core part, such as a generic IC (DIP - 8 pins), and save as new part

- go to Mine bin, right click and select "Save Bin"

- close and reopen Fritzing

- add the new part from Mine bin to an empty project and save the sketch

- close and open Fritzing

- the new part is listed in both Mine bin and Temp bin

I'm using Fritzing v 0.7.12 (b02.13) on Windows XP SP3. I have the same problem with the linux version.

Time: 2013-02-27 09:46:33 UTC

Edited at:

Author: 8

Body:

I am not sure whether to call it a feature or a bug either. It is correct that when you save a sketch, it includes copies of custom parts so that the sketch will still work when you give it to someone else.

A part can appear in multiple bins, so that is also not a problem. However, it may be a special case for the "temp" bin that if a part already exists in "Mine" or elsewhere, it shouldn't appear in temp.  

Is there something about the current state of things that is causing a problem, or is it just that the current behavior is confusing?

 - j

 

 

Time: 2013-02-27 10:50:42 UTC

Edited at:

Author: 9568

Body:

Hi Jonathan,

thanks for your answer.

Well, the "problem" is not something much annoying. As you've written, it's just a little confusing. But I like to understand better what's under the hood, and maybe give you some info about "user experience".

So let's chat a little about this :)

You stated that the Temp bin is something that include custom parts in the current sketch. As you pointed out, that's a good thing for project sharing (and I agree!). Does this mean that I don't need to "attach" fzpz files of custom components when I share a project since that non-standard project are already included in the project itself?

Beside that, I think that it's better to not replicate the component if it's already in another bin, because it looks like it could be a different component or maybe a different version (both newer or older). And than, what's the one I'm using in this project? Well, it must be the Temp one, since this bin was created when I've opened the project. But there could be multiple instance in the sketch and for some (strange) reasons the various instance are from different compoent's versions.

Second thing, are there multiple fzpz files (and/or .svg, .xls, ...) in the Fritzing config directory since there are multiple copy of the component in various bins?

 

I share this questions/remarks with you, and maybe other users could join with their opinion.

Trying not to stress you too much :)

Thanks!

MIX

Time: 2013-02-27 12:13:06 UTC

Edited at:

Author: 8

Body:

Hi MIX,

Thanks for the feedback. 

It is correct that you do not need to attach an fzpz of a custom component to a sketch when you share a project. 

When a part appears in a bin, it is just a pointer, so the mere existence of a part in multiple bins does not necessarily mean there are multiple versions of the parts files. In the case where your custom part is in the Mine bin, and also in the .fzz, the part is loaded from the Mine bin first, so that the sketch "refers" to the part in the Mine bin.

I have added this issue to our issue tracker."

**Comment by KjellMorgenstern** [comment]
If one is not aware that bins contain references to parts, then they might worry if they are the same or somewhat different parts. But this applies to all bins, not only the temp bin.

So, I think it is better to keep it simple stupid, which means if a part is loaded via an fzz, it is referenced in the temp bin, no exceptions. No extra rule like excluding it if it is also in the mine bin.
