### ISSUE TITLE
Fritzing crashes when RoboForm is installed

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2522]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 18, 2013 13:14:18_

http://fritzing.org/forum/thread/1485 One workaround is to add Fritzing to the Roboform's "integrated application blacklist".

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2524_

**Comment by failiz** [comment]
I tried with 0.9.6 and the current RoboForm app. No crashes in Windows. 

I also foundthis in the RoboForm version history:
Version 7.9.0 -- June 26, 2013
* Win32: fix RF is crashing Qt-based Scrivener application. 

Version 7.9.7 -- May 20, 2014
* Win32: fix RF is crashing Qt-based Scrivener application. 

The last comment in this issue is from 2013 and the fix was implemented in 2014. I think it is safe to close this issue.
