### ISSUE TITLE
5-band resistor breadboard image is a little off

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2534]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 26, 2013 07:07:37_

watch what happens when you swap from a 4 band resistor to a 5-band resistor

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2536_

**Comment by KjellMorgenstern** [comment]
This issue is closed due to missing information, inactivity or because it is outdated.
If you think this issue is still important, please provide additional information.
  - What version of Fritzing are you using? 
  - On what operating system?
  - What steps will reproduce the problem? 
  - Screenshots with error messages or rendering issues.  
  - Attach your sketch file and/or custom part files to the bug report. 
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead? 
  - Please use labels and text to provide additional information.
  - Screenshots with error messages
