### ISSUE TITLE
disappearing parts--when changing z order of a wire in bb view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2621]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 11, 2013 12:52:04_

Attached sketch no longer exhibits the behavior. Something is broken in the program state, but saving and loading cleans up the problem. When the striped wire was raised in z-order, the resistor disappeared in bb view. The part was still visible in the other views.

**Attachment:** [DC_motor_control---disapearing parts.fzz](http://code.google.com/p/fritzing/issues/detail?id=2623)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2623_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
