### ISSUE TITLE
Parts rotation confusion

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2632]
_From [casch...@mac.com](https://code.google.com/u/116291006804426827631/) on June 21, 2013 08:27:20_

Sometimes, when choosing multiple parts in ocb view, one can not rotate them with Bauteil-Drehen->um 90° im Uhrzeigersinn drehen. But when you type 90 in the inspector, they rotate by 90°. So it should also work in the menue? What version of Fritzing are you using? On what operating system? 0.8.0 on OS X

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2634_

**Comment by failiz** [comment]
Stil an issue in 0.9.6. Basically, when you click 90 degrees, only one gets selected
A small case of a bigger issue:  #3620. I would close this one as it is a duplicate

**Comment by KjellMorgenstern** [comment]
Could also be as subtask, leaving open on its own for now

**Comment by KjellMorgenstern** [comment]
A selection of parts can be rotated, as a whole, via the menu -> part -> rotate , in 45 degree steps , or 90 degree steps if it is a breadboard or similar.

If you switch to the welcome view, open the part menu, everything is (and should be) disabled.
When you switch back to the Breadboard , Schematic or PCB view, the submenus in the part menu stay disabled.
I think there are also other triggers for this, like when starting fritzing with a project to load.

The issue was in the way the menu structure was created, stored and modified, I am uploading a PR for this.
