### ISSUE TITLE
Feature Request: ratnest lines on pcb should indicate schematic wire size

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2671]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on July 21, 2013 11:23:11_

In the schematic view we can select a width for the wire, however this has little practical purpose as outside of the schematic view there is nothing using this value that I know of.  (See an existing request to have the autorouter consider them).

It would be useful if ratnest lines could indicate the minimum trace size required to satisfy the schematic indicated wire sizes for a given net connection, so that there is visual indication of which connections need to be handled by wider traces.  Less chance of accidentally using an 8mil trace where a 48mil one was specified :)

Dragging a ratnest line to create a trace would also respect that minimum.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2673_

**Comment by failiz** [comment]
I think this will clutter the view with ratsnets of different sizes. It would be better to automatically change the track thickness to the correct one when routing. 
 If accepted, remove imported label

**Comment by KjellMorgenstern** [comment]
Wire and trace width should be aligned across the different views. 
However, the ratsnest line is a logical connection, not a physical. Fritzing might remap the ratsnest to a different connector of the same subnet at any time. In order to avoid clutter, it tries to use the closest connector.

I think "width" makes only sense for connections wich are already routed. Closing.
