### ISSUE TITLE
Changing connectors to pad crashes application

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2712]
_From [jasondho...@gmail.com](https://code.google.com/u/112384894976642079218/) on August 12, 2013 23:08:30_

What steps will reproduce the problem? 1. Creating a new part using Arduino Mega
2. On the connectors tab, when I change it to "pad" the program freezes, and crashes. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2714_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
