### ISSUE TITLE
não existem ligações para rotear

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2761]
_From [info-tec...@hotmail.com](https://code.google.com/u/102894080122351839109/) on October 19, 2013 23:37:16_

Não consigo fazer a ligação dos componentes na protoboard do fritzing
aparece a mensagem. não existem ligações para rotear.e os componentes não se encaixa nos contatos da protoboard.como eu faço para resolver isso

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2763_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
