### ISSUE TITLE
PCB View "Routing completed" is wrong (not detected a connection to be made, missing ratsnest).

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2811]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on December 14, 2013 23:28:21_

Fritzing 0.8.3b
Load the attached fzz

Look in PCB view, you will see it says "Routing Completed"
Notice on the top edge of the board the Arduino Uno pin SCK/D13 is not connected to anything (5th pin from the left along the top edge) in this view.

Switch to schematic view
See that SCK/D13 is connected in this view.

Schematic view is correct, PCB view is incorrect.

The PCB view for some reason refuses to see that connection from SCK/D13 of the Arduino, and reports routing completed even though it's not, PCB view does not provide ratsnest line for it. Even after deleting and recreating the connection in schematic view, the PCB view does not "see" it.

**Attachment:** [Arduino-ISP-Shield-Manual-Tester.fzz](http://code.google.com/p/fritzing/issues/detail?id=2813)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2813_

**Comment by failiz** [comment]
This issue has been solved. There are versions of the Arduino boards with and without the iscp header. Close the issue?
 However, I just noticed that there are three versions of the Arduino Uno rev 3. The last one called "ICSP (w/o icsp2)" had the header in BB and PCB view bit not in the sch view? Should we remove it? In any case, this behind to the parts repository. Should we create an issue in that repository?

**Comment by KjellMorgenstern** [comment]
I think the variants with optional ICSP / ICSP2 headers could be resolved (besides having a part for each variant) with subparts, like issue #3746

**Comment by failiz** [comment]
@KjellMorgenstern, I agree with your comment. However, this issue (as I understood it) is that before there was an Arduino board that had the ISCP connector in the BB and Sch view and not in the PCB view. The third comment says "the d13 pin in schematic view turns out to be the ICSP SCK pin rather than the D13 SCK pin". And the fith, "Hmm, I see, the ICSP header isn't in the PCB but it can be connected to in the BB view (and by this bug in the schematic view)." Now, this has been fixed with versions with and without the ICSP header in all the views.
I do not have the original file, but the second comment specifies a minimal example to replicate the bug: "Can replicate with the simplest case: connect D13 to a pinheader in schematic view, no ratsnest in pcb view." If you try this in 0.9.4, I cannot replicate it.
