### ISSUE TITLE
code that prevents wires from being reconnected to themselves is no longer working

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2871]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 14, 2014 08:03:41_

see comments 1, 2, 3 in issue 2872

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2873_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.

Note: The attachments stored on code.google no longer exist.

If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
