### ISSUE TITLE
LM3914 and LM741

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2930]
_From [cont...@veigamed.com.br](https://code.google.com/u/104940771047981620708/) on March 12, 2014 09:27:54_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2932_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
