### ISSUE TITLE
The export doesn't have a cooper (bottom/top) plus the parts combined view in the export

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2945]
_From [fernaand...@gmail.com](https://code.google.com/u/103843632457594732081/) on April 18, 2014 02:27:56_

What steps will reproduce the problem? 1. export your project to pdf or svg Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? A PDF/SVG with the parts and the cooper layer combined What version of Fritzing are you using? On what operating system? Version 0.8.7 (b1bf5 2014-01-24) Cocoa [Qt 4.8.5]

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2947_

**Comment by failiz** [comment]
Mmm, I guess that what it being asked is for copper+silkscreen combined when you export for production. Is this standard? What is the user case? As a workaround, you can toggle view of the top/bottom layer and export the PCB as a picture. @KjellMorgenstern , is this issue in the pipeline?
In any case, I think this an enhancement rather than a bug. Remove imported label, if accepted.

**Comment by KjellMorgenstern** [comment]
I think this ticket lacks specification about what format is expected, what is the use case. It should not be difficult to combine the exported layers as desired, especially with SVG export.
