### ISSUE TITLE
noconn id tag doesn't work?

### ISSUE THREAD

**Issue by constantinpopp** [fritzing/fritzing-app#3008]
hi all,
i'm trying to create a part with mounting holes. unfortunately i can't get the mounting holes to show up properly in the exported gerber files.
i've seen the in previous posts that "noconn0" as an id could work or "noconnector" could work. i tried both but they still don't show up (following the instructions on the developer webpage regarding the fritzing parts file format). 
you can find the file which needs the mounting holes here: https://dl.dropboxusercontent.com/u/13411946/RK09K.fzpz
 
the inkscape file (which seems not to work) i tried to include the holes you can find here:
https://dl.dropboxusercontent.com/u/13411946/alps%20rk09k%20series%20rotary%20potentiometer3-switched-holes2.svg
 
help would so much appreciated.
 
bests,
const

**Comment by el-j** [comment]
hello const, 

it is not possible, because only a circle element is surely a circle. e.g. an ellipse element cannot be drilled by a normal drill process. so using the circle element for drill holes is the only way to be sure the drill-file has real round drills. otherwise it can cause machine damage or failures during production.

so sadly you have to find a way how inkscape can export circles as circles and not as other elements. 
i found out there is already a discussion and maybe a fix for this inkscape behavior. please have a look at (from 2013):
https://bugs.launchpad.net/inkscape/+bug/377982
http://inkscape.13.x6.nabble.com/Ellipses-Circles-and-Arcs-oh-my-td4968327.html

closed because it's more an inkscape problem
