### ISSUE TITLE
Exporte PNG Image not coherent with schematic

### ISSUE THREAD

**Issue by gratefulfrog** [fritzing/fritzing-app#3070]
I have updated the labels on all my IC chips in a relatively complex schematic. When I export as PNG image the old labels are exported and I cannot find a way to get them to update.

I had noticed this in the past, but it always seemed to "fix itself"? Now however, I cannot seem to get the image to update to conform to the view in the schematic window of Fritzing.

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
