### ISSUE TITLE
Extended Mouse Features

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#308]
_From [reto.wet...@googlemail.com](https://code.google.com/u/107673810697508342868/) on November 25, 2008 05:30:11_

In all design applications, there are some features related to using the
mouse, which are very handy.

For example if you press the shift key, everything will only moved either
horizontally or vertically. This helps as we designers like to clean up our
sketches.

With another key you can duplicate and move a selected object.

Dirk, what else is missing?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=308_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
You can help progress the issue by providing additional information:
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
