### ISSUE TITLE
Wiring perfboard

### ISSUE THREAD

**Issue by tylerhunt** [fritzing/fritzing-app#3105]
I'm finding it very difficult to use the perfboard. Unlike the stripboard, which˙has the ability to cut and build traces, it appears the only way to connect things on the perfboard is to use wires. The issue I'm having, though, is that if I'm trying to wire two components together on the perfboard, it looks like they're connected, but it doesn't appear there's actually a connection made.

How are you supposed to connect components on the perfboard? Am I missing something?

**Comment by htho** [comment]
You can do this with the striped perfboard by clicking between the holes.

**Comment by tylerhunt** [comment]
Right, but if I'm not using a stripboard, that would require me to go through and cut all the traces to make it look like a regular perfboard. Surely there should be a better way to do this. Maybe the default perfboard component should behave like the stripboard and traces to be created.

Why don't wires seem to work properly on perfboards?

**Comment by htho** [comment]
That is why I avoid this view and use the PCB view instead.

**Comment by tylerhunt** [comment]
@htho Again, you're providing workarounds without addressing the actual issue.

**Comment by htho** [comment]
I'd fix it if I was a developer. I am just a user coping with the same issues and sharing my experience with you.

**Comment by tylerhunt** [comment]
@htho Gotcha. Thanks for the suggestions.

**Comment by otede** [comment]
Perfboard seems to be really porked in Fritzing. I constantly get problems with it. See https://github.com/fritzing/fritzing-app/issues/3130

**Comment by aknoerig** [comment]
The perfboard and stripboard aren't really first-class citizens in Fritzing. We added them relatively late in the process, because with the people we talked to everyone was using breadboards.
As you all are showing, perfboards require a different set of interactions, specifically a front/back view and better tools and part designs for the very dense wiring. 
This is no dead end though and could be optimized for the future of course, just not a high priority for us, so any help is welcome

**Comment by otede** [comment]
@aknoerig That's fine, but even with single-side usage there are frequent quirks. Also, a prior notice on the actual state of the said features would be more than welcome.

**Comment by core2zero** [comment]
it's impossible to make a perfboard with a mix of vertical and horizontal traces, half an hour i'm still trying to make the third strip

**Comment by KjellMorgenstern** [comment]
Trying to reproduce the original issue "Wire components together".
It seems to work fine. I tried with a wire and by connecting them on the same hole. Connections were made, and also showed up in schematics and pcb view. Same for stripboard.

While there are some improvements possible, like front / back view and connecting with solder instead of wires, I could not reproduce any problem with connecting or wiring up components.
