### ISSUE TITLE
Label display values change order

### ISSUE THREAD

**Issue by tylerhunt** [fritzing/fritzing-app#3114]
Deselecting the "Label text" display using the "Display Values" contextual submenu and then reselecting it causes it to be added as the last line of the label.

Expected behavior: deselecting the "Label text" display using the "Display Values" contextual submenu and then reselecting it causes it to be added as the first line, which was its original location in the label and corresponds with the position of the items in the contextual submenu.

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
