### ISSUE TITLE
Autoroute Wrong Ratznest Lines

### ISSUE THREAD

**Issue by donperry** [fritzing/fritzing-app#3154]
In ver 092

I used the PCB autoroute functions that then created some ratznest lines that would fry my chips. IS there a way to disable ratznest? At least in the autoroute feature?

The autoroute is the best feauture and i really want to use it without worrying about incorrect ratznest lines.

**Comment by aknoerig** [comment]
The autoroute function shouldn't break your routing. Sometimes it might look like it does, but it's more likely that the "wrong" connection was already there in the first place.

There is no way to disable ratsnests altogether, since it's actually the basis for the autorouting. You can only hide them using the View menu. If it shows ratsnest connections you didn't intend, right-click it to delete them individually.
