### ISSUE TITLE
headers reduction bug

### ISSUE THREAD

**Issue by pippopippo95** [fritzing/fritzing-app#3258]
i've reduced the M40 header from 40 pins to 15 pins, but he is still showing me the same m40 with 40 pins and i can't delete them ''for real'' .

**Comment by KjellMorgenstern** [comment]
Tried to reduce the sparkfun pin header 1x40 to 15 pins, but found only a 16 pin option, which worked fine.

This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
