### ISSUE TITLE
Geber export svg stroke-width bug

### ISSUE THREAD

**Issue by ThomDietrich** [fritzing/fritzing-app#3262]
While defining my own part I stumbled over a nasty bug in the way svgs are converted which only effects the gerber export function and therefor may stay undiscovered before manufacture.

My part got translated to a nice set of lines on silkscreen in pdf or svg export (first image), so everything seemed fine. However the gerber export produced thick unwanted lines (second image).

<img src="https://cloud.githubusercontent.com/assets/2870104/17078608/dce5b052-50f7-11e6-96ca-37e5bdac41e0.png" width="200"><img src="https://cloud.githubusercontent.com/assets/2870104/16701668/87e55c20-4561-11e6-9252-471c98d79754.png" width="200">

The following change in `pcb.svg` was needed to fix that problem for my part: https://github.com/fritzing/fritzing-parts/pull/73/files

**Comment by ThomDietrich** [comment]
Unsure if this is related to and will be solved by https://github.com/fritzing/fritzing-app/pull/3203
@Kazade would you be able to test the part?

**Comment by el-j** [comment]
thanks for point this out. 
it is known that every connector needs his own stroke-width element to export properly. 
the stroke-width element on cooper-group on any other group is not allowed.

this is more a parts issue than a fritzing app-issue. 
the [fritzing-parts](https://github.com/fritzing/fritzing-parts) repository needs automatic checks for such issues. it is planed to do these checks + corrections for every contributed part in future.

close this because of parts-issue

**Comment by ThomDietrich** [comment]
Hey @el-j, closing the ticket in favor of an referencing parts issue would have been fine by me. Without the referencing parts issue you lost this ticket, are you sure that's how you want to deal with this?

**Comment by el-j** [comment]
ok, you are right.
so maybe we can have the issue like that:
https://github.com/fritzing/fritzing-parts/issues/94

closed again ;)

**Comment by ThomDietrich** [comment]
Thanks ;) Keep up the great work
