### ISSUE TITLE
 System Error: "The program can't start because git2.dll is missing from your computer"

### ISSUE THREAD

**Issue by hafizahanun** [fritzing/fritzing-app#3269]
Hi.
I can't open the fritzing software after dowloaded it. Eventhough i have  reinstalled it again and again as instructed so  . A dialogue box appears with this:

"The program can't start because git2.dll is missing from your computer"

What does it mean?
Please help me solving this. 
Thanks!

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - On which operating system? Include exact version numbers and edition.
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
