### ISSUE TITLE
wire color cyan not saved

### ISSUE THREAD

**Issue by zjedi** [fritzing/fritzing-app#3296]
1. select wire color: cyan by right-clicking the wire on breadboard view
2. save project, exit app
3. open app, file -> open recent files -> select my .fzz file
4. the wire colour is not saved. Expected result is seeing a cyan wire, but it remains orange. Same problem exist for schematic view.

using Version 0.9.3 (b5c895d327c44a3114e5fcc9d8260daf0cbb52806 2016-04-19) 64 [Qt 5.6.1] on windows

**Comment by mikeand** [comment]
The predefined colors are stored in [ratsnestcolors.xml](https://github.com/fritzing/fritzing-app/blob/master/resources/ratsnestcolors.xml).

For orange, there are two "obsolete" colors stored. These must be colors used in the past and are no longer used. For orange, one obsolete color is a slightly different orange. The other is just cyan.

When loading the file, it will come across RGB hex values and it tries to convert them to colors. It loops through color values stored in a QHash to work out which color it belongs to. This happens in RatsnestColors::wireColor. 

The result should be slightly random because the QHash randomises the hash value each execution. If it is searching for Cyan \#33ffc5 and comes across Orange before Cyan it will match the RGB hex color to Orange instead of Cyan.

I presume the orange obsolete color with cyan is just a typo and the lines with obsolete names with cyan attached should just be removed from the file.
