### ISSUE TITLE
Feature request: Stripboard better resizing or/and better copy paste support

### ISSUE THREAD

**Issue by DoNck** [fritzing/fritzing-app#3315]
Currently, on v 0.9.3 on Windows 10 64 bits
-setting only the right border (regarding original orientation) of the board is possible to resize the board horizontally 
-setting the lower border (regarding original orientation) of the board is possible to resize the board vertically
-resizing is still very slow and stripe connections are done the wrong way (issue #3162)

**Problems:**

- It is not possible to extend the board from the 2 over 4 borders.
There is no way to move both all components and connections cuts & traces in the same time. No way either to copy/paste both components and cuts & traces to a larger new stripboard.
- If board is firts rotated and then extended, it still extends the same borders, so rotating cannot be used as a workardound to extend the 4 borders
- Setting the layout to wrong vertical/horizontal and then setting back to original value "workaround" completely overwrites any existing cut & bridge work

**Propositions**

- Proposition 1 :
enable resizing using a double arrow cursor on the 4 board borders (breadboard view)

- Proposition 2 :
If proposition 1 is hard to implement, this interface could be used in the inspector view:

| |[+][-]| |
------------ | ------------- | -------------
[+][-] | size: 35x25 | [+][-] 
| |[+][-]| |

Using view orientation would help easy understanding.

- Proposition 3:
Enable copy/paste of components and cut & bridge work to another new larger stripboard (selection using right click&drag)

**Comment by KjellMorgenstern** [comment]
Fritzing 1.0.2 (probably earlier, like Fritzing 0.9.8): Changing the board size keeps cut and bridge work intact. Also, when resizing to a smaller size, and then undoing (edit->undo), cuts and bridges are restored.

Selecting everything, than deselect only the board (Ctrl-Click) , it is possible to move all parts with arrow keys along the grid (which matches the board grid by default).

Since most of the issues described are fixed or have a not so difficult workaround, I am closing this issue.
Please open a new issue for any points that are not yet resolved. Might still be nice to have a resize option with the mouse, like in PCB view boards.
