### ISSUE TITLE
SMD resistor silkscreen on wrong side in hibridy (THT and SMD) one face board.

### ISSUE THREAD

**Issue by youkofoxy** [fritzing/fritzing-app#3345]
I have tried to pass the component name silkscreen to the other side, but it can only be done on duple face boards by changing the component's layer, in one face board always result in the component label being on the wrong side.
beside, the system from time to time treat the one side board as two side.
I have being using the version fritzing.0.9.3b.64.pc on windows seven.

it's possible that the origin of this glitch being dude switching between the two boards type with components still on the board.

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.

  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
