### ISSUE TITLE
search 

### ISSUE THREAD

**Issue by rees52** [fritzing/fritzing-app#3368]
i am not able to find the search option in new version of fritzing 0.9.3 b

**Comment by Intrinsically-Sublime** [comment]
For some reason it sometimes moves to the bottom of the list of parts bins. If you scroll to the bottom of the bins (mine, core, Arduino, Sparkfun,,,,,,,) you should find it at the bottom and then you can drag it back to the top of the list.

**Comment by gromeo** [comment]
Hi,

I've also got this issue; I've installed Fritzing 0.9.3b on two computers, one has win 7, the other one has win 10 with latest updates.
On both PC's I've got this issue: the Search bin appears, but with no field in it so I cannot actually search. The debugging info says "loading bin search".
I've noticed that at every startup the program creates a new copy of the "Mine" and "Search" bins and places them at the bottom of the bin's list, so I've ended up with dozens of copies of the two bins. Please note that only the bins in the program are duplicated: no new my_parts.fzb or search.fzb files are created.
It looks like that a part of the problem is that at the startup the program "thinks" that the two bins do not exist and recreates them (not the files, only the icons in the list).

**Comment by gromeo** [comment]
I have fixed this issue a few days ago. A new release is needed to get the fix or you can compile the source code.

**Comment by KjellMorgenstern** [comment]
I think Giovannis fix is b452175, which is integrated in 0.9.4.
