### ISSUE TITLE
Download link and download page are insecure

### ISSUE THREAD

**Issue by RByers** [fritzing/fritzing-app#3393]
I'd love to use Fritzing for a class Arduino project.  But being a security-aware computer user, I really can't click on a download link from a HTTP web page and install software from it.  Anyone on my network could hijack the connection to insert malware into the download.  Now that SSL certificates [are free](https://letsencrypt.org), there's really no good reason that all downloads at least shouldn't be HTTPS.  Chrome is [increasingly warning](https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure) users about HTTP sites, and warning about executable downloads from HTTP sites is definitely something we hope to do.

For now I'll try to build the project from source myself (at least the GitHub repo is https!).  If that proves difficult I   I encourage anyone who doesn't want their account owned to do the same.

**Comment by KjellMorgenstern** [comment]
Releases will be deployed via github from now on. First development versions are already available via github releases. Not yet recommended for production, since there are just automated development builds, no real releases. Some cosmetic https is also enabled, but really, the software stack running on that server is *old*, so
