### ISSUE TITLE
arts Bin Hidden. Cannot Access Parts At All

### ISSUE THREAD

**Issue by droc101** [fritzing/fritzing-app#3427]
![parts bin gone](https://user-images.githubusercontent.com/37421449/48970025-a24b2280-efcc-11e8-84d7-e7b3398e6566.png)

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please use labels and text to provide additional information.
