### ISSUE TITLE
return twice

### ISSUE THREAD

**Issue by maddin200** [fritzing/fritzing-app#3450]
/src/items/tracewire.cpp line 115     
return result; 
as well line 112

**Comment by vanepp** [comment]
Seems most likely to be a typo since it is dead code and should be optimised out by the compiler. 

Peter

**Comment by KjellMorgenstern** [comment]
It might as well be an merge error from a conflict, and in that case other merge errors might have been introduced at the same time. I checked the corresponding commit, but did not find anything suspicious.

I added "help wanted" since this might be an easy start for newcomers to submit a pull request, but I think I'll just get this out of our feet right now :-)
