### ISSUE TITLE
it isn´t able to allow only one copper layer for the PCB.

### ISSUE THREAD

**Issue by DieTagesschaasch** [fritzing/fritzing-app#3476]

**Comment by KjellMorgenstern** [comment]
This issue is closed due to missing information.
If you think this issue is still important, please provide additional information.
  - What version of Fritzing are you using?
  - On what operating system?
  - What steps will reproduce the problem?
  - Add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
