### ISSUE TITLE
Opening on random screens with i3wm

### ISSUE THREAD

**Issue by noobermin** [fritzing/fritzing-app#3510]
It's possible this might be a i3 issue but this doesn't happen with any other gui application I use currently. Fritzing randomly opens new windows (including opening new sketches) on seemingly random screens when multiple screens are active and on the active workspace for that screen, not the currently active workspace/screen (where the mouse is and i3 is focused). Moreover, it grabs the mouse and moves it to that screen.

As for most tiling window managers i3 can use rules to place windows on preferred workspaces and screens but I have added none for Fritzing.

**Comment by KjellMorgenstern** [comment]
Which version of Fritzing did you use? Can you reproduce the problem with the latest development build? (available via github releases)

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
