### ISSUE TITLE
[LEAP 15.0][Linux] fritzing can't work than once 

### ISSUE THREAD

**Issue by truesoundlord** [fritzing/fritzing-app#3528]
I tried fritzing had time to edit two files and then no way to launch the application again.

![fritzingbug](https://user-images.githubusercontent.com/42813681/65071463-22dd7400-d98f-11e9-8c09-cdacf297399c.png)
![fritzingbug2](https://user-images.githubusercontent.com/42813681/65071469-253fce00-d98f-11e9-8b24-a058b3041f8a.png)
![fritzingbug3](https://user-images.githubusercontent.com/42813681/65071472-27099180-d98f-11e9-981a-f9a1b1c1ea84.png)

I tried to wipe out all related to fritzing and even from clean install the application can not find the parts I just used to create my two fzz files.

**Comment by KjellMorgenstern** [comment]
I guess you were using Fritzing Version 0.9.3beta? If yes, would you like to try the development build? It can downloaded here on github.

**Comment by truesoundlord** [comment]
Sorry I did not dig very far in depth... here this is the beta version, the github version crashes KDE forcing me to kill the "startkde" process to get back to a working environment :{

Workaround: write a bash shell that removes the parts.db file that has a zero byte size.
Once done, the app is able to run each time launched :}

**Comment by KjellMorgenstern** [comment]
Ah, LEAP 15.0 is a Suse Linux. The development version are currently only build for recent Fedora and Ubuntu versions, sorry. Trying to run it on Suse usually should lead to an error because of a missing library, not crash kde.

We don't know why sometimes the parts.db file is corrupted on the old 0.9.3beta. The development build already has a fix to automatically recover from zero size parts.db files.

**Comment by KjellMorgenstern** [comment]
Closing this, as we don't plan to actively provide binaries for all possible Linux distributions. We would however support or integrate AppImages or similar if someone would create such a PR.
