### ISSUE TITLE
Forum software svg upload

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3626]
## Problem

In the previous version of the forum software svgs often didn't upload correctly (and that is still true in the new version.) The work around was to rename file.svg to file.svg.fzp, which did upload correctly and after downloading the "fzp" file, removing the trailing .fzp restored the svg file. 

## Proposed Solution

Most desirable: allow svgs to be uploaded correctly (possibly by not trying to render them?)

More likely: restore the old behaviour of allowing the rename to a fzp file. At present if I rename the svg, the forum software apparently recognizes the   < ?xml line below 

remove_me< ?xml version="1.0" encoding="UTF-8" standalone="no"?>

(note I added blanks after the < above as otherwise it gets taken as markup and I don't know how to avoid that, not knowing markup.)

on first line of the svg and ignores the .fzp and tries to render it (failing.) the above workaround works but is annoying. After down;oading the svg you need to edit it to remove the remove_me text to recover the svg instead of just renaming the file. I don't know what kind of controls are available in the forum software to change that though.

**Comment by KjellMorgenstern** [comment]
I think this is an inherent issue due to the fact that the forum is not really build for file sharing.

However at least one issue is that svgs are rendered to small in some cases, e.g discourse create this 1x2 pixel image.
`![test|1x2](upload://gwZ26LvYGn889D64NiVo349Zqj5.svg) `
When I change it to 100x200, it looks fine.
`![test|100x200](upload://gwZ26LvYGn889D64NiVo349Zqj5.svg) `

See https://forum.fritzing.org/t/lego-powered-up-parts/8594/7

I tried to prohibit svg uploads, but renaming them would still trigger the rendering. Which is actually a not so nice feature.
