### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by deeprobin** [fritzing/fritzing-app#3638]
## Problem
Rust is a very very fast & memory-safe programming language. Yes, I know C++ is also fast but the rust compiler also optimizes the code very well & I think that will be great for this project. For example Tor uses now partly also Rust.

## Proposed Solution
Rewrite the whole project in rust or rewrite some parts in rust

**Comment by KjellMorgenstern** [comment]
I have thought about using the resvg library, replacing the QtSVG library. Not because it is rust, but because it would inter operate with C++ and Qt. 
While the idea is certainly appealing from a dev perspective, I think it does not give enough benefit. Even when backed with the hundred thousands of $ of development time this would cost, I would argue the money would be better invested in improving the existing code base. What kind of investigation did you do to propose this?
