### ISSUE TITLE
voltage value of capacitors not initially showing in the part label

### ISSUE THREAD

**Issue by mMerlin** [fritzing/fritzing-app#3648]
## Current Behaviour

When a capacitor part is placed, it is initially configured to included the voltage in the part label.  According to the "display/values" menu for the part label.  However, the voltage is not actually being displayed.  Turning unchecking and rechecking the voltage in the menu does not have any effect.

This is only being documented for the schematic view, but a quick check says it happens in breadboard and pcb views as well.  Turning on the part label in breadboard view does not show the voltage, unless it has been modified in Inspector.  Here again, the voltage is initially set to display according to the display/values menu.  In pcb view, the voltage is not initially set to be displayed.  Turning it on does not display the voltage, unless it has been modified in the inspector.

Interesting side note.  I just discovered that I can take a screenshot bigger than my physical monitor.  In the VM, setting a screen resolution bigger than the host monitor means (one scenario) scrolling around to see the edges.  However, a screenshot of the current window (on the VM) gets the full defined area/resolution.

initial schematic  view version 0.9.4b
![missing voltage in label-0 9 4b](https://user-images.githubusercontent.com/918823/76819538-15823480-67ce-11ea-8d1d-9db210af34ed.png)

modified voltage of one part in inspector (and change back to initial value)
![changed voltage shows-0 9 4b](https://user-images.githubusercontent.com/918823/76819552-1fa43300-67ce-11ea-9c03-8e0888d10e1c.png)

initial schematic  view version 0.9.5
![missing voltage in label-0 9 5](https://user-images.githubusercontent.com/918823/76819559-2632aa80-67ce-11ea-9402-78b6e15e65f4.png)

modified voltage of one part in inspector (and change back to initial value)
![changed voltage shows-0 9 5](https://user-images.githubusercontent.com/918823/76819569-2f237c00-67ce-11ea-9ce8-446eb23df666.png)

**Build:**
Fritzing version 0.9.4.2019-12-01.CD-498 - Qt version 5.13.2
Version 0.9.5 (dCD-548-1-gcc8758a1 2020-02-15) 64 [Qt 5.13.2]

**Operating System:**
Fedora 31

**Steps to reproduce:**

- place a capacitor part
- examine the part label text
- examine the enabled fields for the text label
- modify the part voltage in Inspector
- see that that the voltage is displayed in the part label

## Expected Behaviour

The voltage should always be displayed when it is enabled in the display/value menu, and the label itself is enabled.

**Comment by failiz** [comment]
I was programming a new feature and I saw that when the calling capacitorItem->getProperty("voltage") returns an empty string. (The inspector showed 6.3V). As soon as I change the value in the inspector, calling capacitorItem->getProperty("voltage")  returns the right value. So, similar issue as the one described here.

The issue seems to be that the voltage field is empty in the part definition. As soon as you write a value in the voltage field and regenerate the database, both issues are fixed. (calling capacitorItem->getProperty("voltage")  returns the right value and the voltage is displayed when you place the component.)

So, the easy fix is to fill some default values in the parts. The right fix would be to find the bug in the code. Interesting, the capacitors are initialized with a voltage of 6.3V, but in properties.xml the default value for capacitors is 35V...

**Comment by KjellMorgenstern** [comment]
Could that be related to PR #3755 ?
I saw the code smell, but don't yet know the issues it might have caused.

**Comment by failiz** [comment]
I do not think so. #3755 seems like an error, but the capacitor class is not based on SymbolPaletteItem class.

I made a PR that fixes the problem #3763
