### ISSUE TITLE
user ic (movable quad and dual opamp) parts loose ratsnest connections when moved to different board sides .

### ISSUE THREAD

**Issue by magstripp-r** [fritzing/fritzing-app#3734]
## user ic (movable quad and dual opamp) parts loose routing connections when moved to different board sides .

<please attach screenshot if possible>
**Build:**
(CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
<Windows 8.1>

**Steps to reproduce:**
- Step 1: go to pcb layout mode
- Step 2: flip pcb side for component 

## Expected Behaviour
connections should be intact.
[new_trap10.zip](https://github.com/fritzing/fritzing-app/files/5425347/new_trap10.zip)

**Comment by vanepp** [comment]
This isn't a Fritzing bug, but rather that the TL074 part you used is incorrectly configured. Here is a corrected part (also posted to the forum post where you got the original part if that is easier) that should correct the problem. The Tl074 part is (among other problems) missing the copper1 definition in all the pcb layer sections fo the .fzp file. To use the part below you will first need to select all the tl074 parts in your sketch and do a delete minus on them. That deletes the part, but leaves the traces connected to it. You then need to delete the TL074 part in your mine parts bin and then shutdown and restart Fritzing to really clear the original part. Then down load the part below, and remove the trailing .zip (this is really a .fzpz file which is zipped but github won't load it without the trailing .zip.) You can then use fiile->open in Fritzing to load the new part and drag that in to your sketch. You then need to grab the end of each of the connections and drag it over the associated pin of the new part to make the connection (it should change from red to green when connected.)

[TL074-Quad-Opamp-(Movable)-improved.fzpz.zip](https://github.com/fritzing/fritzing-app/files/6053661/TL074-Quad-Opamp-.Movable.-improved.fzpz.zip)

You are usually better off to ask about things like this in the Fritzing forums, as you see I rarely remember to read this ...

Peter

**Comment by failiz** [comment]
Not an error. Close

**Comment by KjellMorgenstern** [comment]
The improved part doesn't seem to fix this. Anyway, Fritzing should handle this in some way.

**Comment by vanepp** [comment]
> The improved part doesn't seem to fix this. Anyway, Fritzing should handle this in some way.

My bad! I obviously didn't check the original complaint after fixing the errors in the part. You are correct it still breaks. Moving the part from bottom to top deletes the rats nest lines (which it shouldn't be!) Interestingly, undo will not undo that change as well which I think it should. Hitting undo back to the start does not restore the rats nest lines that were deleted. More problems too. I just tried to do a delete minus in schematic (because I couldn't figure out in pcb which chip the TL074 was and it deleted only the subpart I selected not the entire chip as expected. 

![capture1](https://github.com/fritzing/fritzing-app/assets/16514277/d9e1e2d0-5c0a-4b42-8124-d3d102cb788f)

Do you want to open separate issues on the various issues found or leave them all here (as it is likely all connected to subparts?) If you like I can poke at this failure and figure out all the ways it can fail. It is possible that the bottom of the board rats nest error is a more general issue, or it may be related to only subpart parts. It is fairly unusual to have parts on the bottom of a THT board so there may be a more general issue there or it may be related to only subpart parts. Testing is the only way to find out I expect.  Well the new part loaded all on its own reacts as it should:

![capture2](https://github.com/fritzing/fritzing-app/assets/16514277/36635e11-2963-4445-8472-d72c585792fa)


switching it to the bottom of the board reacts as I would expect (this is with my improved part though, it is possible the original part is causing internal corruption somewhere!) 

![capture3](https://github.com/fritzing/fritzing-app/assets/16514277/b3b90744-012e-4af7-b332-6d5a6c569dc4)

The rats nest lines are still there and connect as expected. I'll continue poking at this and see if I can figure out what is going on. 

edit

OK it appears that most of the problem is in the .fzz file here I did a delete minus on the tl074 part then saved the sketch (to delete the part in the temp parts bin in the .fzz) reloaded the sketch and loaded the new part. I then replaced the part in schematic which should have recreated the rats nest lines in pcb but it does not. 

![capture5](https://github.com/fritzing/fritzing-app/assets/16514277/f7315a1b-290f-4536-85d1-31e5851d76c2)

initially the rats nest lines appear but when the IC is moved from top (where it started) to bottom in pcb the rats nest lines disappear. 

![capture4](https://github.com/fritzing/fritzing-app/assets/16514277/d4918869-a641-40d0-8f09-e9489f448b48)

On a new sketch with the same corrected part it works as expected (mostly anyway there is one new bug!) I think this issue is reported somewhere (the multipart parts show all the subparts in the parts bin but incorrectly) 

![3734-capture2](https://github.com/fritzing/fritzing-app/assets/16514277/9e572d0a-e271-40b8-a099-5c627e0bc403)

schematic is normal and routed 

![3734-capture3](https://github.com/fritzing/fritzing-app/assets/16514277/5bbbaa71-f7c2-426a-9656-32dbad1c4de8)

pcb shows rats nest lines as expected

![3734-capture4](https://github.com/fritzing/fritzing-app/assets/16514277/27015af1-0a49-4c53-9ab9-6f9d8c3fefd7)

when changed from top to bottom of the board in pcb the rats nest lines follow as expected (indicating something about the original .fzz file is corrupted I expect!) 

![3734-capture5](https://github.com/fritzing/fritzing-app/assets/16514277/37648813-6d06-48d8-b578-1ab2af159e40)

doing this does however turn up a new bug: A second copy of the top most schematic subpart (the power supply in this case) gets duplicated in schematic. This one perhaps should get an issue of its own?

![3734-capture6](https://github.com/fritzing/fritzing-app/assets/16514277/e2a7ec61-48d2-4926-810b-bf8de07fc2e4)

this may be the first time I have moved a subpart from the top to the bottom of a board and thus may never have seen this before now.
