### ISSUE TITLE
[FEATURE] Dark theme

### ISSUE THREAD

**Issue by PinkDev1** [fritzing/fritzing-app#3739]
Right now, there are pretty much no theming options on Fritzing, and I'd be really nice if it had them; Prolongued use of fritzing with that `#FFFFFF` background gets tiresome pretty fast

**Comment by KjellMorgenstern** [comment]
Nice to have, but currently unrealistic given the number of open issues.

**Comment by Bluscream** [comment]
Still unrealistic?

**Comment by KaranTrivedi** [comment]
Any updates on this?

**Comment by MimiVRC** [comment]
not having theming options seems to be breaking the app in general now. many things are black deck on a dark gray background because there is no way to force it to just be light mode

**Comment by KjellMorgenstern** [comment]
Colors in Fritzing are determined in many places:
- SVGs from the parts (thousands of files, many more 3rd party files)
- User settings (only very few yet)
- OS settings (themes, dark mode)
- Qt defaults
- Hardcoded within the Code
- Within QSS stylesheets, which can be distinct, specific to OS and Window Manager
- Within generated styles during runtime

It is both, 1. a difficult styling problem. Because of the huge number of elements that need to be restyled, and because just inverting or applying a palette does not work.
2. a big technical problem due to the many different patterns that styles are applied, and not all Operating Systems react similar.

**Comment by sukhmel** [comment]
I would add that some parts change with the system theme, so I have grey text on black background in open file dialog. Changing that was the only reason I looked into changing mode at all:

<img width="759" height="581" alt="Image" src="https://github.com/user-attachments/assets/6c6f6f54-1d1d-4130-9561-ae30ba388670" />

**Comment by KjellMorgenstern** [comment]
> I would add that some parts change with the system theme, so I have grey text on black background in open file dialog. Changing that was the only reason I looked into changing mode at all:

Which exact verison of Fritzing and OS is that? Without this, the information is near to useless (might be 3rd party or old build of Fritzing?)

**Comment by sukhmel** [comment]
@KjellMorgenstern, sorry for not including that

I downloaded it from fritzing.org, about page says:

> Version 1.0.7 
> (CD-2576-0-394a8bb4 2026-04-14) 64 [Qt 6.8.3]

OS info:

> Linux 7.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
> NAME="EndeavourOS"
> ID_LIKE="arch"
> BUILD_ID="2025.03.19"

**Comment by SuperCowProducts** [comment]
So... not gonna happen I guess?
