### ISSUE TITLE
Export as image, toggled layers not honoured

### ISSUE THREAD

**Issue by alex-code** [fritzing/fritzing-app#3771]
## Current Behaviour

Toggling visibility of layers and using `Export->as Image->PNG` or `Export->as Image->JPG`  can show wire artefacts or not export selected layers.

**Example Stripboard**
![image](https://user-images.githubusercontent.com/1797626/102712495-ad5f0280-42b9-11eb-96be-a6e08b76c46d.png)
**After toggling the wire layer visibility**
![image](https://user-images.githubusercontent.com/1797626/102712540-f7e07f00-42b9-11eb-86c5-e377012da57d.png)

I've also had times where unselecting the wires or parts layers, they still appear in the exported imaged.

**Build:**
Version 0.9.4 
(CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
Windows 10

**Steps to reproduce:**
- Create a stripboard sketch
- Toggle layers
- Export as image

## Expected Behaviour
No wire artefacts and only selected layers exported as part of image.

**Comment by failiz** [comment]
I can reproduce this in 0.9.4. Steps to reproduce that I use:
Go to breadboard view and and a wire with a couple of angles over the holes of the breadboard
Toggle the wire layer off
Export as an image (this image is correct)
Toggle the wires layer on 
Export as an image (this image has the artefacts and the wire is missing).

I checked in the latest development version available and this issue is still reproducible.
As soon as yo move the position of the wire, then it exports correctly.

**Comment by failiz** [comment]
already released, close
