### ISSUE TITLE
Install Fritzing via package manager (e.g. brew on macOS)

### ISSUE THREAD

**Issue by moritzmhmk** [fritzing/fritzing-app#3823]
I really understand that the new "pay what you want" option increases the awareness for the costs to develop this awesome software. Nevertheless I missed the new release for quite some time since I used to install Fritzing via "brew cask" (on macOS) and the cask did not get updated yet (since no public download link is available for the new release). I only just realised there was a new release while browsing the documentation for creating new parts.

Since Fritzing is still available for free anyway would it be an option to add downloads to the Github release page again and thus allow for package managers to download the software?

**Comment by KjellMorgenstern** [comment]
Fritzing should have told you about the new version, via the update check. The new version is also announced in the blog. 

The download on our page works on High Sierra, Mojave, Catalina and Big Sur. 
It is a dmg with the typical "drag and drop to install" installer, with an Apple developer certificate to Fritzing GmbH.

We do not provide a free download of Fritzing 0.9.6 binaries. The income from the download is what keeps this project going. After funding (via the Fab, hardware sales, investors and other sources) had ceased, no development happened for multiple years. This left the project with a huge technical debt: open critical issues for > 5 years, a website with an even older software stack (beyond repair) and more. Many of the issues have been solved, and many more will be soon. This is possible because the paid download is widely accepted.
