### ISSUE TITLE
The wiki may be wrong because it fails to build on Windows.

### ISSUE THREAD

**Issue by guilty-gw** [fritzing/fritzing-app#3889]
Even if I follow the wiki, the build does not work at all.
Since the configuration fals for automated builds using AppVeyor and TravisCI have been removed, there is virtually no way to build for Windows despite being OSS.
The owner of the repository should once run it as per the wiki on a clean Windows 10 to see if the build works.
If the build does not work, it proves that the current wiki is wrong.
If the build works, it proves that the current wiki is lacking in instructions on how to build.

**Comment by GuiltyWorks** [comment]
You have made similar comments to others.
Regardless of whether someone wants to develop it or not, the correct way to build it should be described.
No one can ever complete a build in 2 hours to 2 days.

I'm currently finding a few things that need to be fixed in the wiki.
However, I'm not close to completing the build, and I'm not comfortable submitting fixes to the wiki.
At any rate, now that I know you don't intend to fix the wiki, I don't think this conversation will go any further.

If the build is complete, I will submit a fix.

If the build is not complete, I will not submit a fix.
In that case, you may close the issue.
