### ISSUE TITLE
Fritzing App not Scaling Corectly

### ISSUE THREAD

**Issue by Siphowin** [fritzing/fritzing-app#3912]
## Current Behaviour
Text
<img width="960" alt="image" src="https://user-images.githubusercontent.com/45884481/145811846-ec7f9612-2454-464b-8a4a-8952568bc951.png">
**Build:**
0.9.9

**Operating System:**
Windows 11

**Steps to reproduce:**
Install on lenovo Ideapad flex 5 with Win11

## Expected Behaviour
All the Icons are pixelated and the windows aren't properly scaled

**Comment by KjellMorgenstern** [comment]
It works fine on Windows 11. Not enough information to reproduce the problem.

**Comment by KjellMorgenstern** [comment]
Lenovo Ideapad flex 5 comes in 14 and 16 inch variant. We don't know the screen resolution and windows zoom configuration. Additionally, there are no other reports of the problem. 

Please reopen if you can reproduce the problem with Fritzing 0.9.10

**Comment by goncalotr** [comment]
I have the same problem with a flex 5 14 inch
the screen is 1920x1080 and Windows scaling is at 150%

one fix might be to change the scaling individually by using Windows troubleshooter

**Comment by KjellMorgenstern** [comment]
@GoncaloTR So you have a very similar view as in the original screenshot? I would say, if the application is zoomed 150% then larger fonts, icons and bars are expected. Why is it a problem? Or are there problems with some elements not scaling with the rest?

**Comment by goncalotr** [comment]
@KjellMorgenstern the problem is that i do not want the scaling inside the application as it is in Windows since text and graphics are pixilated

That being said, the fix in Fusion 360 was the troubleshooter and this panel (in the image below), which doesn´t solve the problem in this case. Removes the scaling, but the pixelation continues.

![image](https://user-images.githubusercontent.com/66851437/236268045-913edb68-e8e5-4571-81e0-c0ab2513400a.png)

![image](https://user-images.githubusercontent.com/66851437/236268137-32057d2c-70a9-4e5f-b50c-ecc7729147ad.png)
