### ISSUE TITLE
Make it available for installation using the Winget package manager on Windows.

### ISSUE THREAD

**Issue by princebillyGK** [fritzing/fritzing-app#3949]
I can't locate Fritzing in Winget. Please add it to the Winget package manager.

**Comment by KjellMorgenstern** [comment]
This and similar requests are understandable, but they will not turn out well for Fritzing (we tried).
Let me explain in short:

In 2016, development of Fritzing had stopped since all paid developers moved on to other jobs. Side funding (via the Fab, Ads, Kits etc) all are not enough to leave time and money for software development. The project was almost abandoned until we picked up development three years later. This was made possible with the paid downloads at https://fritzing.org/download .  Since then, we were able to restructure the company, reduce the immense backlog in half, rewrite the web services, restart adding parts and even new feature to Fritzing. And of course, provide stable and certified builds, that work on 99% of the various desktop environments. This is successful, and we have been able to improve a lot under the hood, which will allow us to address more user requests in the future. If there are other ways of funding, we will of course check if we can use them.
