### ISSUE TITLE
Simulation error

### ISSUE THREAD

**Issue by Zenande-dev** [fritzing/fritzing-app#3983]
Hey

I am experiencing simulation error and I don’t know how to solve it. Can you please assist
![image](https://user-images.githubusercontent.com/116161452/196658981-f4e9e5f3-980c-4321-871e-de3d2a3d60e7.jpg)

**Comment by failiz** [comment]
It seems that there is no model for the DI_1N4732A. Is this a custom part or a core part? If you can, you could also upload the Fritzing file.

**Comment by Zenande-dev** [comment]
[Fritzing.zip](https://github.com/fritzing/fritzing-app/files/9819804/Fritzing.zip)

**Comment by failiz** [comment]
Thanks for reporting the bug. It is a core part (drop diode from core bin and change it to zener). 

The problem is in the spice field of the part. It is using a subcircuit and the spice line needs to start with X instead with D. It will be fixed in the next release. Until then, if you need a zener diode, you can create a new part.

In any case, remember that the simulator cannot simulate Arduinos. See its capabilities here: https://blog.fritzing.org/2022/06/27/Simulating-Circuits-with-Fritzing

**Comment by failiz** [comment]
The pull request that fixes the issue: https://github.com/fritzing/fritzing-parts/pull/351

**Comment by KjellMorgenstern** [comment]
PR was merged, marking as "solved" unitl we can close this with the 1.0.0 release.
