### ISSUE TITLE
Reading Voltage Impossible?

### ISSUE THREAD

**Issue by shaneparlier** [fritzing/fritzing-app#4009]
# Current Behavior * *Initially posted in Fritzing forum* *
Unable to read the correct voltage when meter is applied correctly to parts with SPICE simulation. Voltage reads 3vdc on simulated open circuit.
<please attach screenshot if possible>
![Fritz1](https://user-images.githubusercontent.com/126843034/222623533-9b8a9012-514d-40e8-80e0-2a5cfe8ea9d7.png)
![Fritz2](https://user-images.githubusercontent.com/126843034/222623547-cc6cbf9b-464d-438c-9505-f4210705702e.png)

**Build:**
Version 0.9.10
(bCD-2134-0-40d23c29 2022-07-01) 64 [Qt 5.15.2]

**Operating System:**
Windows 11 Pro
22621.1265

**Steps to reproduce:**
- Step 1 Create simple circuit with voltmeter attached at appropriate anode/cathode terminal and test with switch simulated open vs closed.

- Step 2 Simulate, voltage should read 0vdc with open circuit, and 3vdc closed (that's not the case in this situation).

## Expected Behavior
Voltage should read 0vdc with open circuit, and 3vdc closed circuit.

**Comment by failiz** [comment]
Thanks for reporting the issue. 
This is due to the spice model of the switch. I used a switch model (see section 3.3.15 and 3.3.16 of the ngspice manual). From the manual:
"The switch model allows an almost ideal switch to be described in ngspice. The switch is not quite ideal, in that the resistance can not change from 0 to infinity, but must always have a finite positive value. By proper selection of the on and off resistances, they can be effectively zero and infinity in comparison to other circuit elements."

In this case, the switch has a resistance of 1m ohm when is closed and 1M ohm when is open. Thus, the simulation is correct but the model is not able to simulate the reality in this case. 

I chose the switch model as a way to allow us to simulate pulsations in a switch when we implement transitory simulations. However, I think we should probably change the model to an open circuit when the switch is released. This will make the simulation correct in these cases. In addition, there are two parts that get swapped (the release and pressed buttons are two parts), so we are not using the switch model of ngspice. We could have a special switch part when we implement transitory analysis. @KjellMorgenstern , do you agree with this change? If so, I will make a pull request.

**Comment by KjellMorgenstern** [comment]
So we would exchange the part because it can not be properly modeled in SPICE ? 
This looks like a red flag, I'd like to discuss this a bit more. 
Are there other situations where the SPICE model needs to be exchanged? 
As I understood, the fix would be so that instead of reporting a high resistance, we don't list the connection at all for simulation. And to achieve this, the plan is to switch the part in Fritzing, like if the user removed it and added another part in place. Is this correct?

**Comment by KjellMorgenstern** [comment]
Also, I don't yet fully understand the problem. If the switch has 1MΩ, shouldn't the voltage drop on the LED be almost zero? This seems kind of too simple, so I am overlooking something here.
Edit ok, got it, of course we have to look at the reverse resistance of the LED.

**Comment by failiz** [comment]
Currently, we already have two parts for every switch that can be simulated. This is done to change the spice field, but also to change the images in the bb and sch views (in sch the switch is closed or open and in bb the button is pressed or not). Thus, the change will only change the spice field of the open switches and it will not be necessary to obsolete the part. 

I agree that this technique is not very elegant, but I did not see many other alternatives as I wanted to change the svg of the part based on the status of the switch. The IR sensor FC-51 also uses this tecnique. In the case of the  FC-51, the images are the same and we could implement something more elegant as the only thing that changes is the spice field. However, this would add more code to the program as the spice field will depend on the status property. I could try to be able to create a spice field that acts conditionally to the status field, but not sure how easy it is.

**Comment by failiz** [comment]
Commit below fixes this issue:
https://github.com/failiz/fritzing-parts/commit/eaa7f61e40952bc514e82b1321c7e3115617fb88

**Comment by shaneparlier** [comment]
Thank you for following up! 🙏

**Comment by KjellMorgenstern** [comment]
Reopening, so we can keep track until the improvement really found its way into Fritzing 1.0.0.

**Comment by KjellMorgenstern** [comment]
Switch now works as expected.
This is a slightly different curcuit then in the OP, but I think it shows the same problem. Before the open switch allowed some voltage drop, which disappears with the new model.
![image](https://github.com/fritzing/fritzing-app/assets/6494025/3f566f1f-00e8-41c1-a818-715733997474)

**Comment by failiz** [comment]
Yes, the problem can become more evident if the resistor is higher (1M ohm), similar to the old spice model of the switch.
