### ISSUE TITLE
No control over connections made over perfboard

### ISSUE THREAD

**Issue by dronus** [fritzing/fritzing-app#4012]
## Current Behaviour
When in breadbord view, connecting a wire from a part or breakout to another one over perfboard connects the wire from the first part's pin to the breadboard "pin". So parts can't be moved around without breaking about half of the connections.

**Build:**
<Version 0.9.6 (b ) 64 [Qt 5.15.2]

**Operating System:**
<Ubuntu 22.04>

**Steps to reproduce:**
- Switch to breadboard view
- Remove breadbord template
- Add some perfoboard
- Place parts over the perfoboard
- Connect pin of those parts
- Move some parts around

## Expected Behaviour
All connections should connect to the parts first, and move with it if part is rotated / moved. Only use the perfoboard "pin" if wires are to be connected to each other.

**Comment by vanepp** [comment]
I'm not clear on what you are asking for here. If I do what you said above it works as expected.

![capture](https://user-images.githubusercontent.com/16514277/225770591-4847e77d-3f54-48ff-a789-66766cedf945.jpg)

if I then move the ic the wires follow (as they won't on a real perfboard though!)

![capture1](https://user-images.githubusercontent.com/16514277/225770839-e1fd4b14-c9aa-42fc-9b93-423e7d832c41.jpg)

If you mean stripboard (which I expect is what you do mean) that is a different case (and more difficult to do!) 

![capture2](https://user-images.githubusercontent.com/16514277/225771270-45bd9b72-0416-483e-86c8-5e11992a3cd0.jpg)

I would argue the moving the IC here acts like real life, only the IC moves not the wires. I expect changing that to be hard in the code, and will break the case where the user wants to move only the IC not all the wires meaning the current operation is probably the better choice. 

![capture3](https://user-images.githubusercontent.com/16514277/225771539-2b3b7e17-b0f6-4c21-b751-97f0b0449e0b.jpg)

**Comment by dronus** [comment]
When I connect a wire _from_ an IC pin, it is attached to the pin. When I connect a wire _to_ an IC pin, it is connected to perfoboard eye instead. As a single wire between two ICs always has a _to_ side, this gives the arbitrary decision which IC the wire should connect to (aka the IC you more likely need to move at some point of design) and which side you connect to board, having the IC only connected as long as it stays in place.

**Comment by vanepp** [comment]
As you see above what you want happens if the wire terminates on the IC pin rather than on the perf board (although that doesn't reflect what typically happens in real life!) Doing that always would likely be difficult (because the perf board and the part are different connections) and more importantly would preclude what is currently possible which is moving an IC that was incorrectly placed although that can have unexpected effects and thus isn't recommended. Here is an example of what can happen. Starting from here where the IC is connected to the perf board pads. 

![capture](https://user-images.githubusercontent.com/16514277/231252713-35a37aaf-2be0-4160-b37c-27a99b0fe978.jpg)

I can correct a placement error by moving the IC one space left 

![capture1](https://user-images.githubusercontent.com/16514277/231253059-1f8ebf7d-d31b-4250-87d3-0e8f6dca8004.jpg)

which I can't do without moving all the wires on the IC probably by deleting and replacing them to make sure they connect to the IC and not the perf board. In the case where the wires are connected to the pins, moving the IC can then create unexpected (and wrong!) connections as the IC will attach to the perf board. Here I connected the wires to the pins

![capture2](https://user-images.githubusercontent.com/16514277/231253777-34e5aecf-81bb-4d71-ba45-e46f1f48e9de.jpg)

then moved the IC (with the wires following.) note when I click on a pad on the resistor perfboard strip all connections (including a new one in the ICs new position) light up as being connected together. 

![capture3](https://user-images.githubusercontent.com/16514277/231254101-905ed20e-eefa-402f-b0f5-20567980d71e.jpg)

If there were already components attached to that perfboard strip you would potentially create a short across a component like this

![capture4](https://user-images.githubusercontent.com/16514277/231255126-ce908fe1-37dd-48f1-b18e-4ef94e699b4a.jpg)

Here we see the resistor has shorted because of the added wire between two perfboard traces and the movement and re connection of the IC to the perf board.  That can still happen now, but it requires that you make the connection to the IC pin (which is uncommon) rather than to the perfboard which is the usual case. As a result I expect there will be reluctance to make such a change (although that isn't my decision.)

**Comment by dronus** [comment]
I think what you are showing is a "strip board" in my nomenclature. What I am talking about is a board with solder dots only, no connections at all, those will be made by wires. So there have wires always connect to pins would be a great benefit, as it would allow move any part around without changing the wiring between them.

**Comment by dronus** [comment]
Even if this is meant for better experience on strip board, it's still abitrary why the "from" connection point is attached to the part, but the "to" connection point is attached to the board.

**Comment by KjellMorgenstern** [comment]
For the perfboard, and without any other definitions like connections in the schematic or PCB, this should not happen:

![image](https://github.com/fritzing/fritzing-app/assets/6494025/be00aadf-24af-4738-a34e-c1196b301b9b)

My guess for why this is happening is that the wire connects either to the perfboard donut or to the IC pin, based on some kind of proximity or history of the mouse drop event.

**Comment by dronus** [comment]
I think it depends on the order of the clicks. The first click seems to always attach to a _pin_, the second one to a donut.
So there is _some_ control, but for any single wire, only _one_ end can be connected to a pin, the other will always connect to the board. That gives headaches on the order of clicks, because if well thought of, some components may be moved later without breaking the netlist, but others not.

**Comment by KjellMorgenstern** [comment]
We had a closer look at this.

If a place has multiple possible connections, they are sorted according to the the method "wireLessThan" in connectoritem.cpp.

Bascially that is:
- Female connectors first (the perfboard or breadboard)
- Then male connectors.
- Then pads.
- Then all others.

For connectors of same type, the z-Order is used.

 When starting the wire, it is possible to exactly select the pin of the IC or the ring of the perfboard.
Only for "To" connections, this is no longer possible.

**Comment by KjellMorgenstern** [comment]
Considering this as a bug. We want to have the control over the target of the connection, same as we have it when starting a wire. 

Besides this, because the highlight elements, the hit box etc all increase in size when zooming in, it still is tricky to select the element, even at high zoom levels. This is a different issue, we already have it at high priority.
