### ISSUE TITLE
Not able to remove bins using the GUI

### ISSUE THREAD

**Issue by failiz** [fritzing/fritzing-app#4064]
## Current Behaviour
Right clik on any of the bins. The menu has options to close and delete the bin, but they are disabled, see picture.
![image](https://github.com/fritzing/fritzing-app/assets/5708642/2f3a4525-ca7d-4aab-94f5-195821570110)
**Build:**
Version 1.0.1 on Windows 10

## Expected Behaviour
Options are enabled and they work.

**Comment by KjellMorgenstern** [comment]
Can you try importing a bin? Eg, Export the "mine" bin , then import it as "test"?

**Comment by failiz** [comment]
with an imported one the options are not disabled and the action works. However, is there a reason to not allow users to remove bins from the app? In fact, you can delete the bin files from the folder where they are installed and then the bins are not shown.

**Comment by KjellMorgenstern** [comment]
The general ux of handling bins could be reviewed, but i think simply enabling the delete for system bins will just cause trouble. It is difficult enough to "debug" the situation when a user has moved a bin to the end of the list and reports that it disappeared. That, and i think other issues like user bin stored in network drives or other removable drives tend to make this quite fragile.

**Comment by failiz** [comment]
I checked this as a user complained in the forum: https://forum.fritzing.org/t/deleting-surplus-bins/20522
Maybe the list of active bins should be configurable in preferences. 
Note: I am not sure what closing means in this context, hides it but the parts are still loaded?

**Comment by KjellMorgenstern** [comment]
It is expected behavior that deleting system bins is not possible.

**Comment by KjellMorgenstern** [comment]
Good point about "Close bin":
```
void BinManager::closeBinIn(int index) {
	if (m_stackTabWidget->count() == 1) return;

	int realIndex = index == -1? m_stackTabWidget->currentIndex(): index;
	PartsBinPaletteWidget *w = getBin(realIndex);
	if((w != nullptr) && w->beforeClosing()) {
		m_stackTabWidget->removeTab(realIndex);
		m_openedBins.remove(w->fileName());
	}
}

```
So, that should remove the bin from the view without deleting the bin file, more similar to what the user requested.  It might even be persisted in the Config. One problem with it thoug, it is not reversible.

Another flow:
1. Choose "Save As" on a bin
2. Now, since the bin was renamed, suddenly it is possible to close it.
3. Close the bin. It is gone.
4. Restart Fritzing, bin is still gone.

Probably it is also possible to delete a bin by choosing "save as" before.
The difference to directly deleting the bin is that no files will be deleted from the installation. All in all, this is not consistent. It would make more sense to enable the "Close", but in this case, we would also need an easy way to "Open" again (besides deleting the settings). 

Closing the bin will be stored in the settings. No easy way to revert :warning:  bins will even stay closed after installing a Fritzing update. Right now, it is not a good idea to use for system bins.

**Comment by failiz** [comment]
Seems reasonable to not tackle this, but maybe we could improve the message to the user. Maybe something adding "(not allowed in core libraries)" to the options disabled?
In any case, we should create a tab in the preferences dialog to allow users to hide the bin (and maybe to specify the order). I have found several times that there are too many bins (especially when the sim bin was at the bottom). Especially as you cannot scroll the bins up and down (scrolling just goes to the next or previous bin), so it is quite tedious. Should I open an enhancement issue for that?

**Comment by KjellMorgenstern** [comment]
Scrolling with the mouse wheel is on my (mental) list, there might be a ticket already, not sure. Should be easy to do now.

Ordering is already possible, just pull the bins with the mouse. Might be worth creating a short video for that, or add it to the Tip of the day.
