### ISSUE TITLE
Incorrect simulation of AND gate

### ISSUE THREAD

**Issue by ayusubov** [fritzing/fritzing-app#4111]
## Current Behaviour
The AND gate circuit (with three NPN BJT transistors) simulation gives wrong results. It works fine with Tinkercad for example. Could not attach the .fzz file. 
![image](https://github.com/fritzing/fritzing-app/assets/6695111/d4af0720-85d5-462e-82e3-01c18f39a27d)
**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
The LED should be off in default state when both switches are released.

**Comment by failiz** [comment]
Rename the fzz file to zip and upload the file. Thanks

**Comment by KjellMorgenstern** [comment]
@ayusubov It would be really helpful to upload the actual sketch. The error might be in the simulator, but it might also caused by other operations, e.g. like starting with a sketch from a broken Fritzing version, or loading a incomplete Fritzing part.

**Comment by ayusubov** [comment]
> Rename the fzz file to zip and upload the file. Thanks

Excellent. Here we are.
[SITE1101-HW01-gate-AND.fzz.zip](https://github.com/fritzing/fritzing-app/files/14170174/SITE1101-HW01-gate-AND.fzz.zip)

**Comment by failiz** [comment]
This circuit does not make sense to me. This is the schematics:
![image](https://github.com/fritzing/fritzing-app/assets/5708642/a772e9fe-3dcf-4b15-9cd2-a059a4120f89)

Please, try to implement another and gate or explain why this circuit should work.

**Comment by ayusubov** [comment]
> This circuit does not make sense to me. This is the schematics: ![image](https://private-user-images.githubusercontent.com/5708642/302557211-a772e9fe-3dcf-4b15-9cd2-a059a4120f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODk2MTgsIm5iZiI6MTcwNzI4OTMxOCwicGF0aCI6Ii81NzA4NjQyLzMwMjU1NzIxMS1hNzcyZTlmZS0zZGNmLTRiMTUtOWNkMi1hMDU5YTQxMjBmODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMDcwMTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZlNzUzOTk5Y2FmMzQ5ZmNlMGEwYjI3OTBkMGEwN2Y1NzY1ZGVmZTc5ZTI1YjBjNzk2MGI3MDFiNjlkMTkxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xt43Tj8aUle4C6ykJStyewtYmZfAKVwEt4IXOV7UiCQ)
> 
> Please, try to implement another and gate or explain why this circuit should work.

Thanks for the follow-up. The schematics does not make sense to me, too, as it is not the intended design. The transistors are NPN ones and unless there is output from the serially connected two, the controlling switch one will be open. Let me double-check. Strangely the "same" design works in Tinkercard and on a real breadboard.

**Comment by ayusubov** [comment]
![image](https://github.com/fritzing/fritzing-app/assets/6695111/fbfa96d8-595e-4721-b715-07b4e4e3b22e)
My schematics does not look as neat, sorry. Does it make more sense now?

**Comment by failiz** [comment]
I think that should work. I made my version of what you tried there and it works correctly. Check it:
[and_transistors.zip](https://github.com/fritzing/fritzing-app/files/14315732/and_transistors.zip)
Note that in your sch when the switches are open, the base of the transistors is floating (in mine they are connected to the ground).
So, I do not think there is a bug in the simulator.

**Comment by ayusubov** [comment]
Dear @failiz thanks a lot for the trouble. When I simulate your circuit, the LED is on by default (with both switches released), which is not right. It is off when both switches are put to the Pressed state :-(

**Comment by failiz** [comment]
Yes, but the switches have pull-up resistors. Thus, when both switches are released, the input to the gate is 9V and 9V and the output is high (around 2.3V due to the LED). If you press one switch, then the input of the gate changes to 0V and the output is low (close to 0V). Thus, the 
![image](https://github.com/fritzing/fritzing-app/assets/5708642/fbe29ca5-f652-4ea3-86cd-1f02f484a072)
The status of the switches does not matter at all, it is the voltage.
You could also change the circuit to pull down resistors to achive the effect that you are looking. See:
https://en.wikipedia.org/wiki/Pull-up_resistor
https://eepower.com/resistor-guide/resistor-applications/pull-up-resistor-pull-down-resistor/#
In any case, this is not a bug of the software.

**Comment by ayusubov** [comment]
Let me get it straight 
- I have downloaded the file you attached, opened it with Fritzing, clicked Simulate, and it does not behave as expected (as an AND gate), in addition it shows smoke over one of the resistors. 
- The original circuit I tried to simulate works as a proper AND gate on actual breadboard, and in Tinkercard simulation, and it does not behave as expected in Fritzing.

**Comment by failiz** [comment]
Let me get it straight. 
The smoke in my circuit is correct, there is too much current for a 1/4 W resistor. You are more than welcome to increase the resistance of that resistor if you want to fix it. 
The AND gate in my file works as an AND gate. The output is HIGH when both inputs are HIGH. 
I cannot debug your breadboard. There are several transistors with different properties and pinouts.
I cannot debug TinkerCAD, it is a proprietary software.
The circuit in the file you submitted does not make sense to both of us.
The picture that you submitted after that is almost identical to my circuit, but the input of the gate are floating when the switches are released, which is not a good design.
The status the switch is irrelevant to the gate. As I said, you can use pull-downs instead of pull-ups to achieve the behaviour that you want. 
Please, give a valid reason to see why my circuit is not working as expected. Truth table for my gate.

INA INB OUT
 H    H    H
 L     H    L
 H    L     L
 L     L     L

**Comment by ayusubov** [comment]
Dear @failiz , the LED is on or off is the effect we are looking for. Fritzing simulation does not turn the LED on only when both switches are Pressed.

**Comment by failiz** [comment]
Dear Araz,
please, change my circuit to use pull-down resistors instead of pull-up resistors for the switches. That will allow the behavior that you want. To do that, simply swap the position of the resistor and the switch for each of the inputs of the gate. 
The state of the switches determines the input signal LOW or HIGH for the gate. In my case, using pull ups, the gate input receives a HIGH signal when they are released. When pressed they receive a LOW signal. 
Best wishes!

**Comment by KjellMorgenstern** [comment]
@failiz Can or should we do something about floating gates? We could detect if any of the connectors used in spice is open, and warn.

**Comment by failiz** [comment]
> @failiz Can or should we do something about floating gates? We could detect if any of the connectors used in spice is open, and warn.

Yes, we could give a warning in case of floating gate inputs or transistor bases. It could be annoying if you have a 4 gate IC and you are only using 1 of them. Not sure if the ad hoc code is worth it un less we have a way to define what is an input, etc.

**Comment by KjellMorgenstern** [comment]
Right, probably not worth it for the limited use cases. It could be part of a more generic DRC improvement, like adding constraints to parts. Such a feature is currently not planned (many other improvements scheduled before that)
