### ISSUE TITLE
Ghost connection when moving a part onto an existing connection

### ISSUE THREAD

**Issue by KjellMorgenstern** [fritzing/fritzing-app#4161]
## Current Behaviour

When moving a connector in top of another connector that already has a wire attached,
then the wire is attached a second time. A  ghost connection is created between J1 and J2.
Deleting the wire resolves the issue, but until this is done, there is unexpected behavior.

**Build:**
Probably all versions, tested on Fritzing 0.9.3 

**Operating System:**
All

**Steps to reproduce:**
1. We start with a wire connected to pin 2 of J1,  same as #4160 
2. Now, add a second connector (J2) and position it on top of J1.
3. Move the connectors apart (mouse or keyboard, doesn't matter)
4. See that there is now a ghost connection between J1 and J2.

Prepare:
![image](https://github.com/user-attachments/assets/3895eb1b-50fb-4478-9adb-af903c07226a)

Add connector on top:
![image](https://github.com/user-attachments/assets/5a44b2ef-cd93-4cf3-8392-ca2715cc8e2d)

Move apart and highlight net (hold mouse on any point of the net)
![image](https://github.com/user-attachments/assets/b202eb6f-a27f-4806-9aac-60e6c96b0d05)

## Expected Behaviour
J2 should not pick up the wire from J1.

**Comment by KjellMorgenstern** [comment]
The effect is similar to #4160. 
While 4160 is more an order of execution error, this one (#4161) points to more generic problems. 
When a part is positioned, it must not pick up  wires that are already connected.

A more general question, not affecting the bugfix (for now we just don't pick up the already connected wire):

Q:What should happen if the wire end is dangling?
Should it attach it when a part is placed on top of the loose wire end?

If we don't connect them, it will be difficult to spot these "cold" connections. But the same applies to parts that are placed on top of each other.

**Comment by vanepp** [comment]
> Q:What should happen if the wire end is dangling?
Should it attach it when a part is placed on top of the loose wire end?

I think it should connect. I believe the rule is that a male connection when moved on to a wire or female connection will connect and I think (but am not sure!) that a wire should be similar, so assuming the part is type male the connection should be made. Indeed that seems to be how 1.0.3 reacts now:

starting  from

![capture](https://github.com/user-attachments/assets/c5abce6d-ca25-42d7-b692-3754165fae7d)

move the header down and it connects to the wire.

![capture1](https://github.com/user-attachments/assets/42097c2b-80c1-40f5-bf49-a0a99191b7d0)

it also connects the other direction

![capture2](https://github.com/user-attachments/assets/d03f3ae1-8510-48e5-8d2b-0aebe77d3ce5)

move the wire to the header and it connects

![capture3](https://github.com/user-attachments/assets/d556c8d1-2cb1-45ad-b724-7032bb4a8969)

move the header (male pin) on to the breadboard

![capture4](https://github.com/user-attachments/assets/7c2258f2-50a3-4410-9b52-04ab3430328e)

and it connects (male header pin moved to female breadboard pin)

![capture5](https://github.com/user-attachments/assets/741a9b0a-636e-4a89-9b1d-e43e9c07e734)

but move the breadboard on to the header (breadboard female to header male) and it doesn't connect

![capture6](https://github.com/user-attachments/assets/1d256c11-4fa9-40c0-a661-30716e0b0b0f)

no connection (because female breadboard moved to male header and that doesn't connect)  

![capture7](https://github.com/user-attachments/assets/067bb378-51ab-4643-a510-f8cc5387ad0a)

I don't know why it works like this, I have always assumed there is a code reason why this needs to be this way, but that may not be correct.

**Comment by failiz** [comment]
> but move the breadboard on to the header (breadboard female to header male) and it doesn't connect
...
> no connection (because female breadboard moved to male header and that doesn't connect)
> 

@vanepp , that is a different issue: https://github.com/fritzing/fritzing-app/issues/3765



> Q:What should happen if the wire end is dangling? Should it attach it when a part is placed on top of the loose wire end?
> 
> If we don't connect them, it will be difficult to spot these "cold" connections. But the same applies to parts that are placed on top of each other.

I think they should connect to avoid the cold connections or, if not, give a warning and let the user select which part will be connected to the wire (but if the cold connector is made is going to be difficult to be spotted by another user, maybe a new color for the "cold" connection?). Parts that are placed on top of each other should connect if one is male and the other is female (as it is done for the shields). If there are two male connectors and a wire, I would say that both connectors should be connected electrically to the wire, and when you move one part, the wire stays with the part that has the "mechanical" connection and thus the two connectors of the part stop being connected electrically.

Maybe a better solution could be to only allow one connection per connector as it happens in the real world: it is not possible to connect a wire in a hole of the breadboard that already has a component (except for screw connectors that could have a few wires). It will force users to use more the breadboard. It will also require that we allow to make Y cables allowing wires to be connected to the bendpoints.

And continuing with replicating the real world, we could just avoid having overlaps of parts in the same layer. I think we now have the breadboard layer, the parts layer and the shields layer. That will solve this issue (probably will trigguer other though)

**Comment by KjellMorgenstern** [comment]
z-order seems to be the key here:
- breadboard over header -> no connection, the breadboard doesn't have anything on the backside.
- header on a breadboard -> connection
- perfboard over male connector... well, this gets interesting. Especially is you consider the long standing and valid feature request, to be able to work on a perf board from both sides.
