### ISSUE TITLE
traces with "don't autoroute" set should have a different color?   (from omer)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#656]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 19, 2009 06:43:29_

or some other way to distinguish them

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=656_

**Comment by KjellMorgenstern** [comment]
Autroroutable and "Don't autoroute"  traces can be selected via the routing menu. This way, the difference can be made temporarily visible.

Closing this for now since there was no further progress or request for a long time. If you think this can be improved, please feel free to reopen or create a new issue.
