### ISSUE TITLE
enable dragging of connected wires (needs better ui)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#678]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 29, 2009 04:01:51_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=678_

**Comment by failiz** [comment]
I do not understand the issue. The connectors of the wires can be dragged (even when they are attached) and therefore, you drag the wire. This is an old issue, so probably it has been implemented since it was reported.
On a side note, I noticed that dragging a connector while pressing Alt or Control avoids the align to grid feature. Is this a feature or a bug?
