### ISSUE TITLE
top-down view option for breadboard and pcb views?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#765]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 21, 2009 01:13:07_

What if we added a top-down svg image for certain parts, then allowed the 
user to switch between 3/4 and top-down views?  The mechanism could be either 
a preference setting, and/or a holding-down-a-key temporary view switch 
(returning to the original view when the key was released).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=765_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
You can help progress the issue by providing additional information:
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.

**Comment by nemccarthy** [comment]
+1 for this feature
