### ISSUE TITLE
parts added to pcb/schematic view should be placed into the breadboard in bbview

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#799]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 02, 2009 10:21:27_

Omer suggests that any part that has all-male connectors, which is first 
placed in schematic or pcb view, gets added to a breadboard in breadboard 
view, rather than simply being placed somewhere unconnected in breadboard 
view.  

My thought would be to add each part to the breadboard horizontally (i.e. 
so no parts would be added that would be directly connected via the 
breadboard's bus).  

Perhaps another rule would be to assume a "ground rail" and a "power rail" 
across the top and bottom of the breadboard, and wire part pins 
accordingly.  This may require including all the ERC metadata in the parts 
files. Are there other rules we could take advantage of?

I'm sure this won't clean up all possible messes, but I think it might 
help. 

Comments?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=799_

**Comment by failiz** [comment]
Not sure if this a good idea. I think that it could be more problematic than helpful.
Imagine that you are building a circui. You have designed half of it in BB view and sch view. You change to the schematic view to build the other half and when you come back to the bbview you will find that the breadboard has been populated with the new parts. You could end up with having to remove the parts from the BB in order to reorganize and build your circuit.

**Comment by KjellMorgenstern** [comment]
Won't implement
