### ISSUE TITLE
complete list of connections on hovering one connector

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#942]
_From [johannes...@googlemail.com](https://code.google.com/u/115332044408901499653/) on November 27, 2009 10:49:29_

If a connector is connected to several other parts, the user can't see that, e.g. in the yellow flyout 
box when hovering over a connector in the sketch. Only one connection is displayed (presumably 
because Fritzing doesn't look for other connections or because the internal logic doesn't provide 
multiple connections by default...)

This is of course also true for the Infoview that (can) displays connections.

For the "new" infoview, it would be possible and nice to show all connections for the inspected 
connector.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=942_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
You can help progress the issue by providing additional information:
  - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - What is the expected output? What do you see instead?
  - Please use labels and text to provide additional information.
